import { useEffect, useMemo, useState } from 'react';
import { api } from '../../api/client';
import { useServer } from '../../state/server';
import type { BuildEntry, Device, DevicesResponse, FlagEntry, FlagsResponse, LaunchConfig, ModelEntry, PreviewCommandResponse } from '../../../../shared/contracts';
import HfSearchPanel from './HfSearchPanel';
import WorkerPanel from './WorkerPanel';

type Form = LaunchConfig & { port: number; cacheTypeK: string; cacheTypeV: string; splitMode: string; rawCommand: string; workerSsh: string };
type Profile = { name: string; config: Form };
const base: Form = { modelPath: '', build: '', ctx: 110000, ngl: 999, port: 8080, fa: true, cacheTypeK: 'q8_0', cacheTypeV: 'q8_0', specType: '', specDraftNMax: 2, specDraftNMin: undefined, specDraftModel: '', specNgramSizeN: undefined, specNgramSizeM: undefined, specNgramMinHits: undefined, specDraftNgl: undefined, preserveThinking: false, reasoningPreserve: false, chatTemplateFile: '', jinja: false, loadMode: '', verbosity: 3, splitMode: 'none', tensorSplit: '50', devices: '', deviceA: '', deviceB: '', transport: 'WiFi', rpcTarget: '', rawCommand: '', argString: '', extraArgs: '', workerSsh: 'kyle4090@169.254.61.173' };
const fieldClass = 'w-full rounded border border-neutral-700 bg-neutral-900 px-2 py-1 text-sm text-neutral-100 disabled:opacity-50';
const specs = ['draft-mtp', 'draft-simple', 'draft-eagle3', 'draft-dflash', 'draft-dspark', 'ngram-simple', 'ngram-map-k', 'ngram-map-k4v', 'ngram-mod', 'ngram-cache'];
function n(value: string): number | undefined { const parsed = Number(value); return value === '' || Number.isNaN(parsed) ? undefined : parsed; }
function saved(key: string, fallback: Profile[]): Profile[] { try { const value: unknown = JSON.parse(localStorage.getItem(key) || '[]'); return Array.isArray(value) ? value as Profile[] : fallback; } catch { return fallback; } }
function storedConfig(): Partial<Form> { try { const value: unknown = JSON.parse(localStorage.getItem('last_launch_config') || '{}'); return value && typeof value === 'object' ? value as Partial<Form> : {}; } catch { return {}; } }
function configFrom(value: LaunchConfig): Partial<Form> { const x = value as LaunchConfig & Record<string, unknown>; return { ...x, cacheTypeK: String(x.cacheTypeK || x.cacheK || 'q8_0'), cacheTypeV: String(x.cacheTypeV || x.cacheV || 'q8_0'), workerSsh: String(x.workerSsh || x.worker_ssh || base.workerSsh), port: typeof x.port === 'number' ? x.port : base.port, rawCommand: String(x.rawCommand || ''), splitMode: String(x.splitMode || 'none') }; }

export default function InteractivePanel() {
 const { state } = useServer();
 const [form, setForm] = useState<Form>(base); const [models, setModels] = useState<ModelEntry[]>([]); const [builds, setBuilds] = useState<BuildEntry[]>([]); const [devices, setDevices] = useState<Device[]>([]); const [profiles, setProfiles] = useState<Profile[]>(() => saved('launch_profiles', []));
 const [loadError, setLoadError] = useState(''); const [actionError, setActionError] = useState(''); const [preview, setPreview] = useState(''); const [previewBusy, setPreviewBusy] = useState(false); const [flags, setFlags] = useState<FlagEntry[]>([]); const [flagOpen, setFlagOpen] = useState(false); const [flagQuery, setFlagQuery] = useState(''); const [advanced, setAdvanced] = useState(false);
 const locked = state?.state !== undefined && state.state !== 'stopped';
 const update = <K extends keyof Form>(key: K, value: Form[K]) => setForm(old => ({ ...old, [key]: value }));
 useEffect(() => { let dead = false; (async () => { try { const [ms, bs] = await Promise.all([api<ModelEntry[]>('/api/models'), api<{ builds: BuildEntry[] }>('/api/builds')]); if (dead) return; setModels(ms); setBuilds(bs.builds || []); const initial = { ...base, ...storedConfig() }; if (!initial.build && bs.builds[0]) initial.build = bs.builds[0].id; if (!initial.modelPath && ms[0]) initial.modelPath = ms[0].path; const ds = await api<DevicesResponse>('/api/devices?build=' + encodeURIComponent(initial.build || '')); if (dead) return; setDevices(ds.devices || []); setForm(initial); } catch (error) { if (!dead) setLoadError(error instanceof Error ? error.message : 'Could not load launch choices.'); } })(); return () => { dead = true; }; }, []);
 useEffect(() => { if (!form.build) return; let dead = false; api<DevicesResponse>('/api/devices?build=' + encodeURIComponent(form.build || '')).then(data => { if (!dead) { setDevices(data.devices || []); if (data.error) setLoadError(data.error); } }).catch(error => { if (!dead) setLoadError(error instanceof Error ? error.message : 'Device discovery failed.'); }); return () => { dead = true; }; }, [form.build]);
 useEffect(() => { if (!state?.launchConfig || !models.length || !builds.length) return; setForm(old => ({ ...old, ...configFrom(state.launchConfig as LaunchConfig) })); }, [state?.launchConfig, models.length, builds.length]);
 useEffect(() => { try { localStorage.setItem('last_launch_config', JSON.stringify(form)); } catch { /* storage failure keeps UI usable */ } }, [form]);
 const specSelected = form.specType ? form.specType.split(',').filter(Boolean) : []; const hasNgram = specSelected.some(item => item.startsWith('ngram-'));
 const filteredFlags = useMemo(() => flags.filter(flag => (flag.flags + ' ' + flag.description + ' ' + flag.section).toLowerCase().includes(flagQuery.toLowerCase())), [flags, flagQuery]);
 async function openFlags() { setActionError(''); setFlagOpen(true); try { const data = await api<FlagsResponse>('/api/flags?build=' + encodeURIComponent(form.build || '')); setFlags(data.flags || []); if (data.error) setActionError(data.error); } catch (error) { setActionError(error instanceof Error ? error.message : 'Could not load flags.'); } }
 function requestConfig(): LaunchConfig { return { ...form, cacheK: form.cacheTypeK, cacheV: form.cacheTypeV, argString: form.extraArgs || form.argString, devices: [form.deviceA, form.deviceB].filter(Boolean).join(','), rpcTarget: form.rpcTarget ? form.workerSsh : '' }; }
 async function previewCommand() { setPreviewBusy(true); setActionError(''); try { const data = await api<PreviewCommandResponse>('/api/preview-command', { method: 'POST', body: JSON.stringify(requestConfig()) }); if (data.error) throw new Error(data.error); setPreview(data.command); update('rawCommand', data.command); } catch (error) { setActionError(error instanceof Error ? error.message : 'Command preview failed.'); } finally { setPreviewBusy(false); } }
 async function start() { setActionError(''); try { await api('/api/start', { method: 'POST', body: JSON.stringify(requestConfig()) }); } catch (error) { setActionError(error instanceof Error ? error.message : 'Start failed.'); } }
 async function stop() { setActionError(''); try { await api('/api/stop', { method: 'POST', body: '{}' }); } catch (error) { setActionError(error instanceof Error ? error.message : 'Stop failed.'); } }
 function saveProfile() { const name = window.prompt('Profile name'); if (!name) return; if (profiles.some(item => item.name === name)) { setActionError('Profile name already exists.'); return; } const next = [...profiles, { name, config: form }]; setProfiles(next); try { localStorage.setItem('launch_profiles', JSON.stringify(next)); } catch { setActionError('Could not save profile.'); } }
 function loadProfile(name: string) { const profile = profiles.find(item => item.name === name); if (!profile) { setActionError('Profile missing.'); return; } setForm({ ...base, ...profile.config }); }
 function deleteProfile(name: string) { const next = profiles.filter(item => item.name !== name); setProfiles(next); try { localStorage.setItem('launch_profiles', JSON.stringify(next)); } catch { setActionError('Could not delete profile.'); } }
 const input = (label: string, key: keyof Form, type = 'text') => <label className="block text-xs text-neutral-400">{label}<input disabled={locked} type={type} value={String(form[key] ?? '')} onChange={event => update(key, type === 'number' ? n(event.target.value) as Form[typeof key] : event.target.value as Form[typeof key])} className={fieldClass} /></label>;
 return <aside className="space-y-4 rounded border border-neutral-800 bg-neutral-900 p-4">
  <div className="flex items-center justify-between"><h2 className="text-sm font-bold text-neutral-200">Launch</h2><HfSearchPanel /></div>
  {loadError && <p role="alert" className="text-xs text-red-400">{loadError}</p>}{actionError && <p role="alert" className="text-xs text-red-400">{actionError}</p>}
  <fieldset disabled={locked} className="space-y-3 disabled:opacity-50"><legend className="sr-only">Launch configuration</legend>
   <div className="flex gap-2"><select aria-label="Load profile" defaultValue="" onChange={event => loadProfile(event.target.value)} className={fieldClass}><option value="">Load saved profile…</option>{profiles.map(profile => <option key={profile.name} value={profile.name}>{profile.name}</option>)}</select><button type="button" onClick={() => deleteProfile((document.activeElement as HTMLSelectElement)?.value || '')} className="rounded bg-red-950 px-2 text-xs text-red-300">Delete</button></div>
   <label className="block text-xs text-neutral-400">Model<select value={form.modelPath} onChange={event => update('modelPath', event.target.value)} className={fieldClass}><option value="">{models.length ? 'Choose model' : 'Loading models…'}</option>{models.map(model => <option key={model.path} value={model.path}>{model.name} ({model.size} GB){model.source === 'huggingface' ? ' [HF cache]' : ''}</option>)}</select></label>
   <label className="block text-xs text-neutral-400">Build<select value={form.build} onChange={event => update('build', event.target.value)} className={fieldClass}>{builds.map(build => <option key={build.id} value={build.id}>{build.label || build.id}</option>)}</select></label>
   <div className="grid grid-cols-2 gap-2"><label className="text-xs text-neutral-400">GPU A<select value={form.deviceA} onChange={event => update('deviceA', event.target.value)} className={fieldClass}><option value="">None</option>{devices.map(device => <option key={device.id} value={device.id}>{device.id} — {device.description}</option>)}</select></label><label className="text-xs text-neutral-400">GPU B<select value={form.deviceB} onChange={event => update('deviceB', event.target.value)} className={fieldClass}><option value="">None</option>{devices.map(device => <option key={device.id} value={device.id}>{device.id} — {device.description}</option>)}</select></label></div>
   <div className="grid grid-cols-2 gap-2">{input('GPU A id', 'deviceA')}{input('GPU B id', 'deviceB')}</div>
   <label className="flex gap-2 text-xs text-indigo-300"><input type="checkbox" checked={Boolean(form.rpcTarget)} onChange={event => update('rpcTarget', event.target.checked ? 'enabled' : '')} />Enable RPC Worker</label>
   {form.rpcTarget && <div className="grid grid-cols-2 gap-2">{input('Worker SSH', 'workerSsh')}<label className="text-xs text-neutral-400">Transport<select value={form.transport} onChange={event => update('transport', event.target.value)} className={fieldClass}><option value="WiFi">Wi-Fi / LAN</option><option value="TB4">Thunderbolt 4</option></select></label></div>}
   <label className="block text-xs text-neutral-400">Tensor split {form.tensorSplit}% / {100 - Number(form.tensorSplit || 50)}%<input type="range" min="0" max="100" value={form.tensorSplit} onChange={event => update('tensorSplit', event.target.value)} className="w-full" /></label>
   <div className="grid grid-cols-3 gap-2">{input('Context', 'ctx', 'number')}{input('GPU layers', 'ngl', 'number')}{input('Port', 'port', 'number')}</div>
   <label className="flex gap-2 text-xs"><input type="checkbox" checked={Boolean(form.fa)} onChange={event => update('fa', event.target.checked)} />Flash Attention</label>
   <div className="grid grid-cols-2 gap-2"><label className="text-xs">Cache K<select value={form.cacheTypeK} onChange={event => update('cacheTypeK', event.target.value)} className={fieldClass}>{['q8_0','f16','q4_0','q4_1'].map(x => <option key={x}>{x}</option>)}</select></label><label className="text-xs">Cache V<select value={form.cacheTypeV} onChange={event => update('cacheTypeV', event.target.value)} className={fieldClass}>{['q8_0','f16','q4_0','q4_1'].map(x => <option key={x}>{x}</option>)}</select></label></div>
   <div><p className="text-xs font-semibold">Speculative decoding</p><div className="grid grid-cols-2 gap-1">{specs.map(spec => <label key={spec} className="text-xs"><input type="checkbox" checked={specSelected.includes(spec)} onChange={event => update('specType', event.target.checked ? [...specSelected, spec].join(',') : specSelected.filter(x => x !== spec).join(','))} /> {spec}</label>)}</div></div>
   {specSelected.length > 0 && <div className="space-y-2 rounded border border-neutral-800 p-2"><div className="grid grid-cols-2 gap-2">{input('Draft N max', 'specDraftNMax', 'number')}{input('Draft N min', 'specDraftNMin', 'number')}</div>{input('Draft model', 'specDraftModel')}{hasNgram && <div className="grid grid-cols-3 gap-2">{input('Ngram N', 'specNgramSizeN', 'number')}{input('Ngram M', 'specNgramSizeM', 'number')}{input('Min hits', 'specNgramMinHits', 'number')}</div>}{input('Draft NGL', 'specDraftNgl', 'number')}</div>}
   <div className="grid grid-cols-2 gap-2"><label className="flex gap-2 text-xs"><input type="checkbox" checked={Boolean(form.preserveThinking)} onChange={event => update('preserveThinking', event.target.checked)} />Preserve thinking</label><label className="flex gap-2 text-xs"><input type="checkbox" checked={Boolean(form.reasoningPreserve)} onChange={event => update('reasoningPreserve', event.target.checked)} />Reasoning preserve</label></div>
   <label className="flex gap-2 text-xs"><input type="checkbox" checked={Boolean(form.jinja)} onChange={event => update('jinja', event.target.checked)} />Jinja template engine</label>{input('Chat template file', 'chatTemplateFile')}
   <div className="grid grid-cols-2 gap-2"><label className="text-xs">Load mode<select value={form.loadMode} onChange={event => update('loadMode', event.target.value)} className={fieldClass}>{['','none','mmap','mlock','mmap+mlock','dio'].map(x => <option key={x} value={x}>{x || 'Default (mmap)'}</option>)}</select></label><label className="text-xs">Verbosity<select value={String(form.verbosity)} onChange={event => update('verbosity', Number(event.target.value))} className={fieldClass}>{[3,4,5].map(x => <option key={x} value={x}>{x}</option>)}</select></label></div>
   <button type="button" onClick={() => setAdvanced(x => !x)} className="w-full rounded bg-neutral-800 p-2 text-xs">Advanced {advanced ? '▲' : '▼'}</button>
   {advanced && <div className="space-y-2"><div className="flex justify-between"><label className="text-xs">Extra args</label><button type="button" onClick={openFlags} className="text-xs text-indigo-300">Flags</button></div><textarea value={form.extraArgs} onChange={event => update('extraArgs', event.target.value)} className={fieldClass} rows={2} /><label className="text-xs">Argument string<input value={form.argString} onChange={event => update('argString', event.target.value)} className={fieldClass} /></label></div>}
  </fieldset>
  <div className="flex gap-2"><button type="button" disabled={previewBusy || locked} onClick={previewCommand} className="rounded bg-neutral-700 px-3 py-2 text-sm disabled:opacity-50">{previewBusy ? 'Previewing…' : 'Preview command'}</button><button type="button" disabled={locked || state?.state !== 'stopped'} onClick={start} className="rounded bg-emerald-700 px-3 py-2 text-sm disabled:opacity-50">Start</button><button type="button" disabled={state?.state === 'stopped'} onClick={stop} className="rounded bg-red-900 px-3 py-2 text-sm disabled:opacity-50">Stop</button><button type="button" disabled={locked} onClick={saveProfile} className="rounded bg-neutral-700 px-3 py-2 text-sm">Save profile</button></div>
  <textarea readOnly aria-label="Launch command preview" value={preview || form.rawCommand} className={fieldClass + ' font-mono text-xs'} rows={4} />{(preview || form.rawCommand) && <button type="button" onClick={() => navigator.clipboard.writeText(preview || form.rawCommand).catch(() => setActionError('Copy failed.'))} className="text-xs text-indigo-300">Copy command</button>}
  {flagOpen && <div role="dialog" aria-modal="true" aria-label="Flag reference" className="fixed inset-4 z-50 overflow-auto rounded border border-neutral-700 bg-neutral-950 p-4"><div className="flex gap-2"><input autoFocus value={flagQuery} onChange={event => setFlagQuery(event.target.value)} placeholder="Search flags" className={fieldClass} /><button type="button" onClick={() => setFlagOpen(false)} className="rounded bg-neutral-800 px-3">Close</button></div><div className="mt-3 space-y-2">{filteredFlags.map(flag => <button type="button" key={flag.primaryFlag} onClick={() => { update('argString', (form.argString + ' ' + flag.insertText).trim()); setFlagOpen(false); }} className="block w-full rounded border border-neutral-800 p-2 text-left text-xs hover:bg-neutral-900"><b>{flag.flags}</b><br />{flag.description}</button>)}</div></div>}
  <WorkerPanel />
 </aside>;
}
