import { useEffect, useState } from 'react';
import { onSseLine, useServer } from '../../state/server';
import SampleDialog from '../shared/SampleDialog';

import { DASH, fmt, fmtDraft } from '../../lib/format';

export default function LiveRequestsPanel() {
    const { completions, progress, state } = useServer(); const [now, setNow] = useState(Date.now()); const [selected, setSelected] = useState<string | null>(null);
    useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 1000); const unsubscribe = onSseLine(() => setNow(Date.now())); return () => { window.clearInterval(timer); unsubscribe(); }; }, []);
    const active = progress && state ? { runId: 'live', timestamp: now, model: state.model || 'Current request', promptTps: progress.prefill ? Number(progress.prefill.tps) : null, genTps: progress.gen ? Number(progress.gen.tps) : null, promptTokens: progress.prefill?.tokens ?? null, genTokens: progress.gen?.tokens ?? null } : null;
    return <section className="rounded-lg border border-neutral-800 bg-neutral-900 p-4"><h2 className="mb-3 text-sm font-semibold text-neutral-200">Requests this session</h2><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-b border-neutral-800 text-neutral-500"><tr><th className="p-2">Time</th><th className="p-2">Model</th><th className="p-2">Prompt</th><th className="p-2">Gen</th><th className="p-2">Wall</th><th className="p-2">Draft accept / accepted / generated / mean len</th><th className="p-2">Status</th><th className="p-2">Samples</th></tr></thead><tbody>{active && <tr className="border-b border-neutral-800 text-amber-300"><td className="p-2">Live</td><td className="p-2">{active.model}</td><td className="p-2">{active.promptTokens ?? DASH} @ {fmt(active.promptTps)}</td><td className="p-2">{active.genTokens ?? DASH} @ {fmt(active.genTps)}</td><td className="p-2">…</td><td className="p-2">{DASH}</td><td className="p-2">In flight</td><td className="p-2">{DASH}</td></tr>}{completions.map(row => <tr key={row.runId} className="border-b border-neutral-800 text-neutral-300"><td className="p-2">{new Date(row.timestamp).toLocaleTimeString()}</td><td className="max-w-48 truncate p-2" title={row.model}>{row.model}</td><td className="p-2">{row.promptTokens ?? DASH} @ {fmt(row.promptTps)}</td><td className="p-2">{row.genTokens ?? DASH} @ {fmt(row.genTps)}</td><td className="p-2">{fmt(row.wallTime)}s</td><td className="p-2">{fmtDraft(row)}</td><td className="p-2">{row.aborted ? <span className="rounded bg-red-950 px-1 text-red-300">Aborted</span> : 'Done'}</td><td className="p-2"><button type="button" onClick={() => setSelected(row.runId)} className="text-indigo-300 hover:underline">View</button></td></tr>)}</tbody></table></div>{!active && completions.length === 0 && <p className="py-6 text-center text-sm text-neutral-500">No requests completed since this page loaded.</p>}{selected && <SampleDialog runId={selected} onClose={() => setSelected(null)} />}</section>;
}