// Auto-generated by scripts/gen-params.ts from llama-server --help.
// Do not hand-edit defaults/flags/env/help - regenerate.
// Hand-correct labels/groups/options/scope where marked TODO.
// Source build: 2026-08-26T18:31:43.074Z - 248 params
export type ParamScope = 'request' | 'server' | 'archive';
export type ParamGroup =
  | 'speed' | 'memory' | 'context' | 'sampling' | 'model' | 'devices'
  | 'speculative' | 'server' | 'agents' | 'multimodal' | 'chat' | 'logging' | 'archive';

export type ParamControl = 'int' | 'float' | 'text' | 'toggle' | 'enum' | 'multi-enum' | 'path' | 'list';

export interface ParamDef {
  id: string;
  label: string;
  flags: string[];
  env?: string;
  group: ParamGroup;
  scope: ParamScope;
  control: ParamControl;
  default?: unknown;
  defaultLabel?: string;
  min?: number; max?: number; step?: number; unit?: string;
  options?: { value: string; label?: string }[];
  runtime?: 'device-list';
  help: string;
  docUrl?: string;
  deprecated?: { since?: string; replacedBy?: string };
  requiresRestart?: boolean;
}

export const LLAMA_PARAMS: ParamDef[] = [
  {
    id: "cpu_mask",
    label: "CPU Mask",
    flags: [
      "-C",
      "--cpu-mask"
    ],
    group: "speed",
    scope: "server",
    control: "text",
    default: "",
    help: "CPU affinity mask: arbitrarily long hex.",
    requiresRestart: true
  },
  {
    id: "cpu_mask_batch",
    label: "CPU Mask Batch",
    flags: [
      "-Cb",
      "--cpu-mask-batch"
    ],
    group: "speed",
    scope: "server",
    control: "text",
    defaultLabel: "same as --cpu-mask",
    help: "CPU affinity mask: arbitrarily long hex.",
    requiresRestart: true
  },
  {
    id: "cpu_range",
    label: "CPU Range",
    flags: [
      "-Cr",
      "--cpu-range"
    ],
    group: "speed",
    scope: "server",
    control: "text",
    help: "range of CPUs for affinity.",
    requiresRestart: true
  },
  {
    id: "cpu_range_batch",
    label: "CPU Range Batch",
    flags: [
      "-Crb",
      "--cpu-range-batch"
    ],
    group: "speed",
    scope: "server",
    control: "text",
    help: "ranges of CPUs for affinity.",
    requiresRestart: true
  },
  {
    id: "cpu_strict",
    label: "CPU Strict",
    flags: [
      "--cpu-strict"
    ],
    group: "speed",
    scope: "server",
    control: "enum",
    default: 0,
    options: [
      {
        value: "0"
      },
      {
        value: "1"
      }
    ],
    help: "use strict CPU placement",
    requiresRestart: true
  },
  {
    id: "cpu_strict_batch",
    label: "CPU Strict Batch",
    flags: [
      "--cpu-strict-batch"
    ],
    group: "speed",
    scope: "server",
    control: "enum",
    defaultLabel: "same as --cpu-strict",
    options: [
      {
        value: "0"
      },
      {
        value: "1"
      }
    ],
    help: "use strict CPU placement",
    requiresRestart: true
  },
  {
    id: "no_cont_batching",
    label: "No Cont Batching",
    flags: [
      "-cb",
      "--cont-batching",
      "-nocb",
      "--no-cont-batching"
    ],
    env: "LLAMA_ARG_CONT_BATCHING",
    group: "speed",
    scope: "server",
    control: "toggle",
    default: "enabled",
    help: "whether to enable continuous batching (a.k.a dynamic batching)",
    requiresRestart: true
  },
  {
    id: "parallel",
    label: "Parallel",
    flags: [
      "-np",
      "--parallel"
    ],
    env: "LLAMA_ARG_N_PARALLEL",
    group: "speed",
    scope: "server",
    control: "int",
    default: -1,
    defaultLabel: "auto",
    help: "number of server slots",
    requiresRestart: true
  },
  {
    id: "poll",
    label: "Poll",
    flags: [
      "--poll"
    ],
    group: "speed",
    scope: "server",
    control: "text",
    help: "use polling level to wait for work (0 - no polling, default: 50)",
    requiresRestart: true
  },
  {
    id: "poll_batch",
    label: "Poll Batch",
    flags: [
      "--poll-batch"
    ],
    group: "speed",
    scope: "server",
    control: "enum",
    defaultLabel: "same as --poll",
    options: [
      {
        value: "0"
      },
      {
        value: "1"
      }
    ],
    help: "use polling to wait for work",
    requiresRestart: true
  },
  {
    id: "prio",
    label: "Prio",
    flags: [
      "--prio"
    ],
    group: "speed",
    scope: "server",
    control: "int",
    default: 0,
    help: "set process/thread priority : low(-1), normal(0), medium(1), high(2), realtime(3)",
    requiresRestart: true
  },
  {
    id: "prio_batch",
    label: "Prio Batch",
    flags: [
      "--prio-batch"
    ],
    group: "speed",
    scope: "server",
    control: "int",
    default: 0,
    help: "set process/thread priority : 0-normal, 1-medium, 2-high, 3-realtime",
    requiresRestart: true
  },
  {
    id: "threads",
    label: "Threads",
    flags: [
      "-t",
      "--threads"
    ],
    env: "LLAMA_ARG_THREADS",
    group: "speed",
    scope: "server",
    control: "int",
    default: -1,
    help: "number of CPU threads to use during generation",
    requiresRestart: true
  },
  {
    id: "threads_batch",
    label: "Threads Batch",
    flags: [
      "-tb",
      "--threads-batch"
    ],
    group: "speed",
    scope: "server",
    control: "text",
    defaultLabel: "same as --threads",
    help: "number of threads to use during batch and prompt processing",
    requiresRestart: true
  },
  {
    id: "threads_http",
    label: "Threads Http",
    flags: [
      "--threads-http"
    ],
    env: "LLAMA_ARG_THREADS_HTTP",
    group: "speed",
    scope: "server",
    control: "int",
    default: -1,
    help: "number of threads used to process HTTP requests",
    requiresRestart: true
  },
  {
    id: "cache_type_k_draft",
    label: "Cache Type K Draft",
    flags: [
      "--spec-draft-type-k",
      "-ctkd",
      "--cache-type-k-draft"
    ],
    env: "LLAMA_ARG_SPEC_DRAFT_CACHE_TYPE_K",
    group: "memory",
    scope: "server",
    control: "enum",
    default: "f16",
    options: [
      {
        value: "f32"
      },
      {
        value: "f16"
      },
      {
        value: "bf16"
      },
      {
        value: "q8_0"
      },
      {
        value: "q4_0"
      },
      {
        value: "q4_1"
      },
      {
        value: "iq4_nl"
      },
      {
        value: "q5_0"
      },
      {
        value: "q5_1"
      }
    ],
    help: "KV cache data type for K for the draft model",
    requiresRestart: true
  },
  {
    id: "cache_type_v_draft",
    label: "Cache Type V Draft",
    flags: [
      "--spec-draft-type-v",
      "-ctvd",
      "--cache-type-v-draft"
    ],
    env: "LLAMA_ARG_SPEC_DRAFT_CACHE_TYPE_V",
    group: "memory",
    scope: "server",
    control: "enum",
    default: "f16",
    options: [
      {
        value: "f32"
      },
      {
        value: "f16"
      },
      {
        value: "bf16"
      },
      {
        value: "q8_0"
      },
      {
        value: "q4_0"
      },
      {
        value: "q4_1"
      },
      {
        value: "iq4_nl"
      },
      {
        value: "q5_0"
      },
      {
        value: "q5_1"
      }
    ],
    help: "KV cache data type for V for the draft model",
    requiresRestart: true
  },
  {
    id: "check_tensors",
    label: "Check Tensors",
    flags: [
      "--check-tensors"
    ],
    group: "memory",
    scope: "server",
    control: "toggle",
    default: "false",
    help: "check model tensor data for invalid values",
    requiresRestart: true
  },
  {
    id: "cpu_moe",
    label: "CPU Moe",
    flags: [
      "-cmoe",
      "--cpu-moe"
    ],
    env: "LLAMA_ARG_CPU_MOE",
    group: "memory",
    scope: "server",
    control: "text",
    help: "keep all Mixture of Experts (MoE) weights in the CPU",
    requiresRestart: true
  },
  {
    id: "fit",
    label: "Fit",
    flags: [
      "-fit",
      "--fit"
    ],
    env: "LLAMA_ARG_FIT",
    group: "memory",
    scope: "server",
    control: "enum",
    options: [
      {
        value: "on"
      },
      {
        value: "off"
      }
    ],
    help: "whether to adjust unset arguments to fit in device memory ('on' or 'off', default: 'on')",
    requiresRestart: true
  },
  {
    id: "fit_ctx",
    label: "Fit CTX",
    flags: [
      "-fitc",
      "--fit-ctx"
    ],
    env: "LLAMA_ARG_FIT_CTX",
    group: "memory",
    scope: "server",
    control: "text",
    help: "minimum ctx size that can be set by --fit option, default: 4096",
    requiresRestart: true
  },
  {
    id: "fit_target",
    label: "Fit Target",
    flags: [
      "-fitt",
      "--fit-target"
    ],
    env: "LLAMA_ARG_FIT_TARGET",
    group: "memory",
    scope: "server",
    control: "list",
    runtime: "device-list",
    help: "target margin per device for --fit, comma-separated list of values, single value is broadcast across all devices, default: 1024",
    requiresRestart: true
  },
  {
    id: "keep",
    label: "Keep",
    flags: [
      "--keep"
    ],
    group: "memory",
    scope: "request",
    control: "int",
    default: 0,
    defaultLabel: "-1 = all",
    help: "number of tokens to keep from the initial prompt"
  },
  {
    id: "cache_type_k",
    label: "KV cache type K",
    flags: [
      "-ctk",
      "--cache-type-k"
    ],
    env: "LLAMA_ARG_CACHE_TYPE_K",
    group: "memory",
    scope: "server",
    control: "enum",
    default: "f16",
    options: [
      {
        value: "f32"
      },
      {
        value: "f16"
      },
      {
        value: "bf16"
      },
      {
        value: "q8_0"
      },
      {
        value: "q4_0"
      },
      {
        value: "q4_1"
      },
      {
        value: "iq4_nl"
      },
      {
        value: "q5_0"
      },
      {
        value: "q5_1"
      }
    ],
    help: "KV cache data type for K",
    requiresRestart: true
  },
  {
    id: "cache_type_v",
    label: "KV cache type V",
    flags: [
      "-ctv",
      "--cache-type-v"
    ],
    env: "LLAMA_ARG_CACHE_TYPE_V",
    group: "memory",
    scope: "server",
    control: "enum",
    default: "f16",
    options: [
      {
        value: "f32"
      },
      {
        value: "f16"
      },
      {
        value: "bf16"
      },
      {
        value: "q8_0"
      },
      {
        value: "q4_0"
      },
      {
        value: "q4_1"
      },
      {
        value: "iq4_nl"
      },
      {
        value: "q5_0"
      },
      {
        value: "q5_1"
      }
    ],
    help: "KV cache data type for V",
    requiresRestart: true
  },
  {
    id: "load_mode",
    label: "Load Mode",
    flags: [
      "-lm",
      "--load-mode"
    ],
    env: "LLAMA_ARG_LOAD_MODE",
    group: "memory",
    scope: "server",
    control: "enum",
    default: "auto",
    help: "model loading mode - auto: mmap, unless a device does not support it - none: no special loading mode - mmap: memory-map model (if mmap disabled, slower load but may reduce pageouts if not using mlock) - mlock: force system to keep model in RAM rather than swapping or compressi...",
    requiresRestart: true
  },
  {
    id: "n_cpu_moe",
    label: "N CPU Moe",
    flags: [
      "-ncmoe",
      "--n-cpu-moe"
    ],
    env: "LLAMA_ARG_N_CPU_MOE",
    group: "memory",
    scope: "server",
    control: "text",
    help: "keep the Mixture of Experts (MoE) weights of the first N layers in the CPU",
    requiresRestart: true
  },
  {
    id: "no_host",
    label: "No Host",
    flags: [
      "--no-host"
    ],
    env: "LLAMA_ARG_NO_HOST",
    group: "memory",
    scope: "server",
    control: "toggle",
    help: "bypass host buffer allowing extra buffers to be used",
    requiresRestart: true
  },
  {
    id: "numa",
    label: "NUMA",
    flags: [
      "--numa"
    ],
    env: "LLAMA_ARG_NUMA",
    group: "memory",
    scope: "server",
    control: "text",
    help: "attempt optimizations that help on some NUMA systems - distribute: spread execution evenly over all nodes - isolate: only spawn threads on CPUs on the node that execution started on - numactl: use the CPU map provided by numactl if run without this previously, it is recommende...",
    requiresRestart: true
  },
  {
    id: "override_tensor",
    label: "Override Tensor",
    flags: [
      "-ot",
      "--override-tensor"
    ],
    env: "LLAMA_ARG_OVERRIDE_TENSOR",
    group: "memory",
    scope: "server",
    control: "text",
    help: "override tensor buffer type",
    requiresRestart: true
  },
  {
    id: "swa_full",
    label: "Swa Full",
    flags: [
      "--swa-full"
    ],
    env: "LLAMA_ARG_SWA_FULL",
    group: "memory",
    scope: "server",
    control: "toggle",
    default: "false",
    help: "use full-size SWA cache [(more info)](https://github.com/ggml-org/llama.cpp/pull/13194#issuecomment-2868343055)",
    requiresRestart: true
  },
  {
    id: "batch_size",
    label: "Batch Size",
    flags: [
      "-b",
      "--batch-size"
    ],
    env: "LLAMA_ARG_BATCH",
    group: "context",
    scope: "server",
    control: "int",
    default: 2048,
    help: "logical maximum batch size",
    requiresRestart: true
  },
  {
    id: "cache_ram",
    label: "Cache Ram",
    flags: [
      "-cram",
      "--cache-ram"
    ],
    env: "LLAMA_ARG_CACHE_RAM",
    group: "context",
    scope: "server",
    control: "int",
    default: 8192,
    defaultLabel: "-1 - no limit, 0 - disable",
    help: "set the maximum cache size in MiB [(more info)](https://github.com/ggml-org/llama.cpp/pull/16391)",
    requiresRestart: true
  },
  {
    id: "checkpoint_min_step",
    label: "Checkpoint Min Step",
    flags: [
      "-cms",
      "--checkpoint-min-step"
    ],
    env: "LLAMA_ARG_CHECKPOINT_MIN_SPACING_NT",
    group: "context",
    scope: "server",
    control: "int",
    default: 8192,
    defaultLabel: "0 = no minimum",
    help: "minimum spacing between context checkpoints in tokens",
    requiresRestart: true
  },
  {
    id: "ctx_size",
    label: "Context size",
    flags: [
      "-c",
      "--ctx-size"
    ],
    env: "LLAMA_ARG_CTX_SIZE",
    group: "context",
    scope: "server",
    control: "int",
    default: 0,
    defaultLabel: "loaded from model",
    help: "size of the prompt context",
    requiresRestart: true
  },
  {
    id: "rope_freq_base",
    label: "ROPE Freq Base",
    flags: [
      "--rope-freq-base"
    ],
    env: "LLAMA_ARG_ROPE_FREQ_BASE",
    group: "context",
    scope: "server",
    control: "text",
    default: "loaded from model",
    help: "RoPE base frequency, used by NTK-aware scaling",
    requiresRestart: true
  },
  {
    id: "rope_freq_scale",
    label: "ROPE Freq Scale",
    flags: [
      "--rope-freq-scale"
    ],
    env: "LLAMA_ARG_ROPE_FREQ_SCALE",
    group: "context",
    scope: "server",
    control: "text",
    help: "RoPE frequency scaling factor, expands context by a factor of 1/N",
    requiresRestart: true
  },
  {
    id: "rope_scale",
    label: "ROPE Scale",
    flags: [
      "--rope-scale"
    ],
    env: "LLAMA_ARG_ROPE_SCALE",
    group: "context",
    scope: "server",
    control: "text",
    help: "RoPE context scaling factor, expands context by a factor of N",
    requiresRestart: true
  },
  {
    id: "rope_scaling",
    label: "ROPE Scaling",
    flags: [
      "--rope-scaling"
    ],
    env: "LLAMA_ARG_ROPE_SCALING_TYPE",
    group: "context",
    scope: "server",
    control: "enum",
    options: [
      {
        value: "none"
      },
      {
        value: "linear"
      },
      {
        value: "yarn"
      }
    ],
    help: "RoPE frequency scaling method, defaults to linear unless specified by the model",
    requiresRestart: true
  },
  {
    id: "ubatch_size",
    label: "Ubatch Size",
    flags: [
      "-ub",
      "--ubatch-size"
    ],
    env: "LLAMA_ARG_UBATCH",
    group: "context",
    scope: "server",
    control: "int",
    default: 512,
    help: "physical maximum batch size",
    requiresRestart: true
  },
  {
    id: "yarn_attn_factor",
    label: "YARN Attn Factor",
    flags: [
      "--yarn-attn-factor"
    ],
    env: "LLAMA_ARG_YARN_ATTN_FACTOR",
    group: "context",
    scope: "server",
    control: "int",
    default: -1,
    help: "YaRN: scale sqrt(t) or attention magnitude",
    requiresRestart: true
  },
  {
    id: "yarn_beta_fast",
    label: "YARN Beta Fast",
    flags: [
      "--yarn-beta-fast"
    ],
    env: "LLAMA_ARG_YARN_BETA_FAST",
    group: "context",
    scope: "server",
    control: "int",
    default: -1,
    help: "YaRN: low correction dim or beta",
    requiresRestart: true
  },
  {
    id: "yarn_beta_slow",
    label: "YARN Beta Slow",
    flags: [
      "--yarn-beta-slow"
    ],
    env: "LLAMA_ARG_YARN_BETA_SLOW",
    group: "context",
    scope: "server",
    control: "int",
    default: -1,
    help: "YaRN: high correction dim or alpha",
    requiresRestart: true
  },
  {
    id: "yarn_ext_factor",
    label: "YARN Ext Factor",
    flags: [
      "--yarn-ext-factor"
    ],
    env: "LLAMA_ARG_YARN_EXT_FACTOR",
    group: "context",
    scope: "server",
    control: "int",
    default: -1,
    defaultLabel: "0.0 = full interpolation",
    help: "YaRN: extrapolation mix factor",
    requiresRestart: true
  },
  {
    id: "yarn_orig_ctx",
    label: "YARN Orig CTX",
    flags: [
      "--yarn-orig-ctx"
    ],
    env: "LLAMA_ARG_YARN_ORIG_CTX",
    group: "context",
    scope: "server",
    control: "int",
    default: 0,
    defaultLabel: "model training context size",
    help: "YaRN: original context size of model",
    requiresRestart: true
  },
  {
    id: "adaptive_decay",
    label: "Adaptive Decay",
    flags: [
      "--adaptive-decay"
    ],
    group: "sampling",
    scope: "request",
    control: "float",
    default: 0.9,
    help: "adaptive-p: decay rate for target adaptation over time."
  },
  {
    id: "adaptive_target",
    label: "Adaptive Target",
    flags: [
      "--adaptive-target"
    ],
    group: "sampling",
    scope: "request",
    control: "int",
    default: -1,
    help: "adaptive-p: select tokens near this probability (valid range 0.0 to 1.0; negative = disabled) [(more info)](https://github.com/ggml-org/llama.cpp/pull/17927)"
  },
  {
    id: "backend_sampling",
    label: "Backend Sampling",
    flags: [
      "-bs",
      "--backend-sampling"
    ],
    env: "LLAMA_ARG_BACKEND_SAMPLING",
    group: "sampling",
    scope: "request",
    control: "toggle",
    default: "disabled",
    help: "enable backend sampling (experimental)"
  },
  {
    id: "cache_reuse",
    label: "Cache Reuse",
    flags: [
      "--cache-reuse"
    ],
    env: "LLAMA_ARG_CACHE_REUSE",
    group: "sampling",
    scope: "request",
    control: "int",
    default: 0,
    help: "min chunk size to attempt reusing from the cache via KV shifting, requires prompt caching to be enabled [(card)](https://ggml.ai/f0.png)"
  },
  {
    id: "dry_allowed_length",
    label: "Dry Allowed Length",
    flags: [
      "--dry-allowed-length"
    ],
    group: "sampling",
    scope: "request",
    control: "int",
    default: 2,
    help: "set allowed length for DRY sampling"
  },
  {
    id: "dry_base",
    label: "Dry Base",
    flags: [
      "--dry-base"
    ],
    group: "sampling",
    scope: "request",
    control: "float",
    default: 1.75,
    help: "set DRY sampling base value"
  },
  {
    id: "dry_multiplier",
    label: "Dry Multiplier",
    flags: [
      "--dry-multiplier"
    ],
    group: "sampling",
    scope: "request",
    control: "int",
    default: 0,
    defaultLabel: "0.0 = disabled",
    help: "set DRY sampling multiplier"
  },
  {
    id: "dry_penalty_last_n",
    label: "Dry Penalty Last N",
    flags: [
      "--dry-penalty-last-n"
    ],
    group: "sampling",
    scope: "request",
    control: "float",
    default: 64,
    defaultLabel: "0 = disable",
    help: "set DRY penalty for the last n tokens"
  },
  {
    id: "dry_sequence_breaker",
    label: "Dry Sequence Breaker",
    flags: [
      "--dry-sequence-breaker"
    ],
    group: "sampling",
    scope: "request",
    control: "text",
    help: "add sequence breaker for DRY sampling, clearing out default breakers ('\\n', ':', '\"', '*') in the process; use \"none\" to not use any sequence breakers"
  },
  {
    id: "dynatemp_exp",
    label: "Dynatemp Exp",
    flags: [
      "--dynatemp-exp"
    ],
    group: "sampling",
    scope: "request",
    control: "float",
    default: 1,
    help: "dynamic temperature exponent"
  },
  {
    id: "dynatemp_range",
    label: "Dynatemp Range",
    flags: [
      "--dynatemp-range"
    ],
    group: "sampling",
    scope: "request",
    control: "float",
    default: 0,
    defaultLabel: "0.0 = disabled",
    help: "dynamic temperature range"
  },
  {
    id: "frequency_penalty",
    label: "Frequency Penalty",
    flags: [
      "--frequency-penalty"
    ],
    group: "sampling",
    scope: "request",
    control: "float",
    default: 0,
    defaultLabel: "0.0 = disabled",
    help: "repeat alpha frequency penalty"
  },
  {
    id: "grammar",
    label: "Grammar",
    flags: [
      "--grammar"
    ],
    group: "sampling",
    scope: "request",
    control: "text",
    help: "BNF-like grammar to constrain generations (see samples in grammars/ dir)"
  },
  {
    id: "grammar_file",
    label: "Grammar File",
    flags: [
      "--grammar-file"
    ],
    group: "sampling",
    scope: "request",
    control: "path",
    help: "file to read grammar from"
  },
  {
    id: "ignore_eos",
    label: "Ignore Eos",
    flags: [
      "--ignore-eos"
    ],
    group: "sampling",
    scope: "request",
    control: "toggle",
    help: "ignore end of stream token and continue generating (implies --logit-bias EOS-inf)"
  },
  {
    id: "json_schema",
    label: "Json Schema",
    flags: [
      "-j",
      "--json-schema"
    ],
    group: "sampling",
    scope: "request",
    control: "text",
    help: "JSON schema to constrain generations (https://json-schema.org/), e.g."
  },
  {
    id: "json_schema_file",
    label: "Json Schema File",
    flags: [
      "-jf",
      "--json-schema-file"
    ],
    group: "sampling",
    scope: "request",
    control: "path",
    help: "File containing a JSON schema to constrain generations (https://json-schema.org/), e.g."
  },
  {
    id: "logit_bias",
    label: "Logit Bias",
    flags: [
      "-l",
      "--logit-bias"
    ],
    group: "sampling",
    scope: "request",
    control: "text",
    help: "modifies the likelihood of token appearing in the completion, i.e."
  },
  {
    id: "min_p",
    label: "Min P",
    flags: [
      "--min-p"
    ],
    group: "sampling",
    scope: "request",
    control: "float",
    default: 0.05,
    defaultLabel: "0.0 = disabled",
    help: "min-p sampling"
  },
  {
    id: "mirostat",
    label: "Mirostat",
    flags: [
      "--mirostat"
    ],
    group: "sampling",
    scope: "request",
    control: "int",
    default: 0,
    defaultLabel: "disabled, 1 = Mirostat, 2 = Mirostat 2.0",
    help: "use Mirostat sampling."
  },
  {
    id: "mirostat_ent",
    label: "Mirostat Ent",
    flags: [
      "--mirostat-ent"
    ],
    group: "sampling",
    scope: "request",
    control: "int",
    default: 5,
    help: "Mirostat target entropy, parameter tau"
  },
  {
    id: "mirostat_lr",
    label: "Mirostat Lr",
    flags: [
      "--mirostat-lr"
    ],
    group: "sampling",
    scope: "request",
    control: "float",
    default: 0.1,
    help: "Mirostat learning rate, parameter eta"
  },
  {
    id: "presence_penalty",
    label: "Presence Penalty",
    flags: [
      "--presence-penalty"
    ],
    group: "sampling",
    scope: "request",
    control: "float",
    default: 0,
    defaultLabel: "0.0 = disabled",
    help: "repeat alpha presence penalty"
  },
  {
    id: "repeat_last_n",
    label: "Repeat Last N",
    flags: [
      "--repeat-last-n"
    ],
    group: "sampling",
    scope: "request",
    control: "int",
    default: 64,
    defaultLabel: "0 = disabled",
    help: "last n tokens to consider for penalize"
  },
  {
    id: "repeat_penalty",
    label: "Repeat Penalty",
    flags: [
      "--repeat-penalty"
    ],
    group: "sampling",
    scope: "request",
    control: "float",
    default: 1,
    defaultLabel: "1.0 = disabled",
    help: "penalize repeat sequence of tokens"
  },
  {
    id: "samplers",
    label: "Samplers",
    flags: [
      "--samplers"
    ],
    group: "sampling",
    scope: "request",
    control: "text",
    default: "penalties",
    defaultLabel: "dry, top_n_sigma, top_k, typ_p, top_p, min_p, xtc, temperature",
    help: "samplers that will be used for generation in the order, separated by ';'"
  },
  {
    id: "sampling_seq",
    label: "Sampling Seq",
    flags: [
      "--sampler-seq",
      "--sampling-seq"
    ],
    group: "sampling",
    scope: "request",
    control: "text",
    default: "edskypmxt",
    help: "simplified sequence for samplers that will be used"
  },
  {
    id: "seed",
    label: "Seed",
    flags: [
      "-s",
      "--seed"
    ],
    group: "sampling",
    scope: "request",
    control: "int",
    default: -1,
    defaultLabel: "use random seed for -1",
    help: "RNG seed"
  },
  {
    id: "temperature",
    label: "Temperature",
    flags: [
      "--temp",
      "--temperature"
    ],
    group: "sampling",
    scope: "request",
    control: "float",
    default: 0.8,
    help: "temperature"
  },
  {
    id: "n_predict",
    label: "Tokens to predict",
    flags: [
      "-n",
      "--predict",
      "--n-predict"
    ],
    env: "LLAMA_ARG_N_PREDICT",
    group: "sampling",
    scope: "request",
    control: "int",
    default: -1,
    defaultLabel: "infinity",
    help: "number of tokens to predict"
  },
  {
    id: "top_k",
    label: "Top K",
    flags: [
      "--top-k"
    ],
    env: "LLAMA_ARG_TOP_K",
    group: "sampling",
    scope: "request",
    control: "int",
    default: 40,
    defaultLabel: "0 = disabled",
    help: "top-k sampling"
  },
  {
    id: "top_n_sigma",
    label: "Top N Sigma",
    flags: [
      "--top-nsigma",
      "--top-n-sigma"
    ],
    group: "sampling",
    scope: "request",
    control: "int",
    default: -1,
    defaultLabel: "-1.0 = disabled",
    help: "top-n-sigma sampling"
  },
  {
    id: "top_p",
    label: "Top P",
    flags: [
      "--top-p"
    ],
    group: "sampling",
    scope: "request",
    control: "float",
    default: 0.95,
    defaultLabel: "1.0 = disabled",
    help: "top-p sampling"
  },
  {
    id: "typical_p",
    label: "Typical P",
    flags: [
      "--typical",
      "--typical-p"
    ],
    group: "sampling",
    scope: "request",
    control: "float",
    default: 1,
    defaultLabel: "1.0 = disabled",
    help: "locally typical sampling, parameter p"
  },
  {
    id: "xtc_probability",
    label: "Xtc Probability",
    flags: [
      "--xtc-probability"
    ],
    group: "sampling",
    scope: "request",
    control: "float",
    default: 0,
    defaultLabel: "0.0 = disabled",
    help: "xtc probability"
  },
  {
    id: "xtc_threshold",
    label: "Xtc Threshold",
    flags: [
      "--xtc-threshold"
    ],
    group: "sampling",
    scope: "request",
    control: "float",
    default: 0.1,
    defaultLabel: "1.0 = disabled",
    help: "xtc threshold"
  },
  {
    id: "alias",
    label: "Alias",
    flags: [
      "-a",
      "--alias"
    ],
    env: "LLAMA_ARG_ALIAS",
    group: "model",
    scope: "server",
    control: "text",
    help: "set model name aliases, comma-separated (to be used by API)",
    requiresRestart: true
  },
  {
    id: "cache_list",
    label: "Cache List",
    flags: [
      "-cl",
      "--cache-list"
    ],
    group: "model",
    scope: "server",
    control: "text",
    help: "show list of models in cache",
    requiresRestart: true
  },
  {
    id: "completion_bash",
    label: "Completion Bash",
    flags: [
      "--completion-bash"
    ],
    group: "model",
    scope: "server",
    control: "toggle",
    help: "print source-able bash completion script for llama.cpp",
    requiresRestart: true
  },
  {
    id: "control_vector",
    label: "Control Vector",
    flags: [
      "--control-vector"
    ],
    group: "model",
    scope: "server",
    control: "text",
    help: "add a control vector note: use comma-separated values to add multiple control vectors",
    requiresRestart: true
  },
  {
    id: "control_vector_layer_range",
    label: "Control Vector Layer Range",
    flags: [
      "--control-vector-layer-range"
    ],
    group: "model",
    scope: "server",
    control: "text",
    help: "layer range to apply the control vector(s) to, start and end inclusive",
    requiresRestart: true
  },
  {
    id: "control_vector_scaled",
    label: "Control Vector Scaled",
    flags: [
      "--control-vector-scaled"
    ],
    group: "model",
    scope: "server",
    control: "text",
    help: "add a control vector with user defined scaling SCALE note: use comma-separated values (format: FNAME:SCALE,...)",
    requiresRestart: true
  },
  {
    id: "docker_repo",
    label: "Docker Repo",
    flags: [
      "-dr",
      "--docker-repo"
    ],
    env: "LLAMA_ARG_DOCKER_REPO",
    group: "model",
    scope: "server",
    control: "text",
    default: "unused",
    help: "Docker Hub model repository.",
    requiresRestart: true
  },
  {
    id: "embeddings",
    label: "Embeddings",
    flags: [
      "--embedding",
      "--embeddings"
    ],
    env: "LLAMA_ARG_EMBEDDINGS",
    group: "model",
    scope: "server",
    control: "toggle",
    default: "disabled",
    help: "restrict to only support embedding use case; use only with dedicated embedding models",
    requiresRestart: true
  },
  {
    id: "flash_attn",
    label: "Flash Attn",
    flags: [
      "-fa",
      "--flash-attn"
    ],
    env: "LLAMA_ARG_FLASH_ATTN",
    group: "model",
    scope: "server",
    control: "enum",
    options: [
      {
        value: "on"
      },
      {
        value: "off"
      },
      {
        value: "auto"
      }
    ],
    help: "set Flash Attention use ('on', 'off', or 'auto', default: 'auto')",
    requiresRestart: true
  },
  {
    id: "gpt_oss_120b_default",
    label: "Gpt Oss 120b Default",
    flags: [
      "--gpt-oss-120b-default"
    ],
    group: "model",
    scope: "server",
    control: "toggle",
    help: "use gpt-oss-120b (note: can download weights from the internet)",
    requiresRestart: true
  },
  {
    id: "gpt_oss_20b_default",
    label: "Gpt Oss 20b Default",
    flags: [
      "--gpt-oss-20b-default"
    ],
    group: "model",
    scope: "server",
    control: "toggle",
    help: "use gpt-oss-20b (note: can download weights from the internet)",
    requiresRestart: true
  },
  {
    id: "hf_file",
    label: "HF File",
    flags: [
      "-hff",
      "--hf-file"
    ],
    env: "LLAMA_ARG_HF_FILE",
    group: "model",
    scope: "server",
    control: "path",
    default: "unused",
    help: "Hugging Face model file.",
    requiresRestart: true
  },
  {
    id: "hf_repo",
    label: "HF Repo",
    flags: [
      "-hf",
      "-hfr",
      "--hf-repo"
    ],
    env: "LLAMA_ARG_HF_REPO",
    group: "model",
    scope: "server",
    control: "text",
    default: "unused",
    help: "Hugging Face model repository; quant is optional, case-insensitive, default to Q4_K_M, or falls back to the first file in the repo if Q4_K_M doesn't exist.",
    requiresRestart: true
  },
  {
    id: "hf_repo_draft",
    label: "HF Repo Draft",
    flags: [
      "--spec-draft-hf",
      "-hfd",
      "-hfrd",
      "--hf-repo-draft"
    ],
    env: "LLAMA_ARG_SPEC_DRAFT_HF_REPO",
    group: "model",
    scope: "server",
    control: "text",
    default: "unused",
    help: "Same as --hf-repo, but for the draft model",
    requiresRestart: true
  },
  {
    id: "hf_token",
    label: "HF Token",
    flags: [
      "-hft",
      "--hf-token"
    ],
    env: "HF_TOKEN",
    group: "model",
    scope: "server",
    control: "text",
    default: "value from HF_TOKEN environment variable",
    help: "Hugging Face access token",
    requiresRestart: true
  },
  {
    id: "lookup_cache_dynamic",
    label: "Lookup Cache Dynamic",
    flags: [
      "-lcd",
      "--lookup-cache-dynamic"
    ],
    group: "model",
    scope: "server",
    control: "path",
    help: "path to dynamic lookup cache to use for lookup decoding (updated by generation)",
    requiresRestart: true
  },
  {
    id: "lookup_cache_static",
    label: "Lookup Cache Static",
    flags: [
      "-lcs",
      "--lookup-cache-static"
    ],
    group: "model",
    scope: "server",
    control: "path",
    help: "path to static lookup cache to use for lookup decoding (not updated by generation)",
    requiresRestart: true
  },
  {
    id: "lora",
    label: "LORA",
    flags: [
      "--lora"
    ],
    group: "model",
    scope: "server",
    control: "path",
    help: "path to LoRA adapter (use comma-separated values to load multiple adapters)",
    requiresRestart: true
  },
  {
    id: "lora_init_without_apply",
    label: "LORA Init Without Apply",
    flags: [
      "--lora-init-without-apply"
    ],
    group: "model",
    scope: "server",
    control: "toggle",
    default: "disabled",
    help: "load LoRA adapters without applying them (apply later via POST /lora-adapters)",
    requiresRestart: true
  },
  {
    id: "lora_scaled",
    label: "LORA Scaled",
    flags: [
      "--lora-scaled"
    ],
    group: "model",
    scope: "server",
    control: "path",
    help: "path to LoRA adapter with user defined scaling (format: FNAME:SCALE,...) note: use comma-separated values",
    requiresRestart: true
  },
  {
    id: "model",
    label: "Model",
    flags: [
      "-m",
      "--model"
    ],
    env: "LLAMA_ARG_MODEL",
    group: "model",
    scope: "server",
    control: "path",
    help: "model path to load",
    requiresRestart: true
  },
  {
    id: "model_url",
    label: "Model URL",
    flags: [
      "-mu",
      "--model-url"
    ],
    env: "LLAMA_ARG_MODEL_URL",
    group: "model",
    scope: "server",
    control: "text",
    default: "unused",
    help: "model download url",
    requiresRestart: true
  },
  {
    id: "no_agent",
    label: "No Agent",
    flags: [
      "-ag",
      "--agent",
      "-no-ag",
      "--no-agent"
    ],
    env: "LLAMA_ARG_AGENT",
    group: "model",
    scope: "server",
    control: "toggle",
    default: "disabled",
    help: "whether to enable CORS proxy and all built-in tools - do not enable in untrusted environments note: for security reasons, this will limit --cors-origins to localhost by default",
    requiresRestart: true
  },
  {
    id: "no_cache_idle_slots",
    label: "No Cache Idle Slots",
    flags: [
      "--cache-idle-slots",
      "--no-cache-idle-slots"
    ],
    env: "LLAMA_ARG_CACHE_IDLE_SLOTS",
    group: "model",
    scope: "server",
    control: "toggle",
    default: "enabled",
    defaultLabel: "requires cache-ram",
    help: "save idle slots to the prompt cache on new task, and clear them when using unified KV",
    requiresRestart: true
  },
  {
    id: "no_cache_prompt",
    label: "No Cache Prompt",
    flags: [
      "--cache-prompt",
      "--no-cache-prompt"
    ],
    env: "LLAMA_ARG_CACHE_PROMPT",
    group: "model",
    scope: "request",
    control: "toggle",
    default: "enabled",
    help: "whether to enable prompt caching"
  },
  {
    id: "no_context_shift",
    label: "No Context Shift",
    flags: [
      "--context-shift",
      "--no-context-shift"
    ],
    env: "LLAMA_ARG_CONTEXT_SHIFT",
    group: "model",
    scope: "server",
    control: "toggle",
    default: "disabled",
    help: "whether to use context shift on infinite text generation",
    requiresRestart: true
  },
  {
    id: "no_cors_credentials",
    label: "No Cors Credentials",
    flags: [
      "--cors-credentials",
      "--no-cors-credentials"
    ],
    env: "LLAMA_ARG_CORS_CREDENTIALS",
    group: "model",
    scope: "server",
    control: "toggle",
    default: "enabled",
    help: "whether to allow credentials for CORS note: if this is enabled and --cors-origins is set to * (default), the Origin header will be echoed back, and credentials will always be allowed",
    requiresRestart: true
  },
  {
    id: "no_escape",
    label: "No Escape",
    flags: [
      "-e",
      "--escape",
      "--no-escape"
    ],
    group: "model",
    scope: "server",
    control: "toggle",
    default: "true",
    help: "whether to process escapes sequences (\\n, \\r, \\t, \\', \\\", \\\\)",
    requiresRestart: true
  },
  {
    id: "no_jinja",
    label: "No JINJA",
    flags: [
      "--jinja",
      "--no-jinja"
    ],
    env: "LLAMA_ARG_JINJA",
    group: "model",
    scope: "server",
    control: "toggle",
    default: "enabled",
    help: "whether to use jinja template engine for chat",
    requiresRestart: true
  },
  {
    id: "no_kv_offload",
    label: "No KV Offload",
    flags: [
      "-kvo",
      "--kv-offload",
      "-nkvo",
      "--no-kv-offload"
    ],
    env: "LLAMA_ARG_KV_OFFLOAD",
    group: "model",
    scope: "server",
    control: "toggle",
    default: "enabled",
    help: "whether to enable KV cache offloading",
    requiresRestart: true
  },
  {
    id: "no_kv_unified",
    label: "No KV Unified",
    flags: [
      "-kvu",
      "--kv-unified",
      "-no-kvu",
      "--no-kv-unified"
    ],
    env: "LLAMA_ARG_KV_UNIFIED",
    group: "model",
    scope: "server",
    control: "text",
    default: "enabled if number of slots is auto",
    help: "use single unified KV buffer shared across all sequences",
    requiresRestart: true
  },
  {
    id: "no_log_prefix",
    label: "No Log Prefix",
    flags: [
      "--log-prefix",
      "--no-log-prefix"
    ],
    env: "LLAMA_ARG_LOG_PREFIX",
    group: "model",
    scope: "server",
    control: "text",
    help: "Enable prefix in log messages",
    requiresRestart: true
  },
  {
    id: "no_log_timestamps",
    label: "No Log Timestamps",
    flags: [
      "--log-timestamps",
      "--no-log-timestamps"
    ],
    env: "LLAMA_ARG_LOG_TIMESTAMPS",
    group: "model",
    scope: "server",
    control: "text",
    help: "Enable timestamps in log messages",
    requiresRestart: true
  },
  {
    id: "no_mmproj_auto",
    label: "No MMPROJ Auto",
    flags: [
      "--mmproj-auto",
      "--no-mmproj",
      "--no-mmproj-auto"
    ],
    env: "LLAMA_ARG_MMPROJ_AUTO",
    group: "model",
    scope: "server",
    control: "toggle",
    default: "enabled",
    help: "whether to use multimodal projector file (if available), useful when using -hf",
    requiresRestart: true
  },
  {
    id: "no_mmproj_offload",
    label: "No MMPROJ Offload",
    flags: [
      "--mmproj-offload",
      "--no-mmproj-offload"
    ],
    env: "LLAMA_ARG_MMPROJ_OFFLOAD",
    group: "model",
    scope: "server",
    control: "toggle",
    default: "enabled",
    help: "whether to enable GPU offloading for multimodal projector",
    requiresRestart: true
  },
  {
    id: "no_models_autoload",
    label: "No Models Autoload",
    flags: [
      "--models-autoload",
      "--no-models-autoload"
    ],
    env: "LLAMA_ARG_MODELS_AUTOLOAD",
    group: "model",
    scope: "server",
    control: "toggle",
    default: "enabled",
    help: "for router server, whether to automatically load models",
    requiresRestart: true
  },
  {
    id: "no_op_offload",
    label: "No Op Offload",
    flags: [
      "--op-offload",
      "--no-op-offload"
    ],
    group: "model",
    scope: "server",
    control: "toggle",
    default: "true",
    help: "whether to offload host tensor operations to device",
    requiresRestart: true
  },
  {
    id: "no_perf",
    label: "No Perf",
    flags: [
      "--perf",
      "--no-perf"
    ],
    env: "LLAMA_ARG_PERF",
    group: "model",
    scope: "server",
    control: "toggle",
    default: "false",
    help: "whether to enable internal libllama performance timings",
    requiresRestart: true
  },
  {
    id: "no_prefill_assistant",
    label: "No Prefill Assistant",
    flags: [
      "--prefill-assistant",
      "--no-prefill-assistant"
    ],
    env: "LLAMA_ARG_PREFILL_ASSISTANT",
    group: "model",
    scope: "server",
    control: "text",
    default: "prefill enabled",
    help: "whether to prefill the assistant's response if the last message is an assistant message when this flag is set, if the last message is an assistant message then it will be treated as a full message and not prefilled",
    requiresRestart: true
  },
  {
    id: "no_repack",
    label: "No Repack",
    flags: [
      "--repack",
      "-nr",
      "--no-repack"
    ],
    env: "LLAMA_ARG_REPACK",
    group: "model",
    scope: "server",
    control: "toggle",
    default: "enabled",
    help: "whether to enable weight repacking",
    requiresRestart: true
  },
  {
    id: "no_slots",
    label: "No Slots",
    flags: [
      "--slots",
      "--no-slots"
    ],
    env: "LLAMA_ARG_ENDPOINT_SLOTS",
    group: "model",
    scope: "server",
    control: "toggle",
    default: "enabled",
    help: "expose slots monitoring endpoint",
    requiresRestart: true
  },
  {
    id: "no_warmup",
    label: "No Warmup",
    flags: [
      "--warmup",
      "--no-warmup"
    ],
    group: "model",
    scope: "server",
    control: "toggle",
    default: "enabled",
    help: "whether to perform warmup with an empty run",
    requiresRestart: true
  },
  {
    id: "no_webui",
    label: "No Webui",
    flags: [
      "--ui",
      "--webui",
      "--no-ui",
      "--no-webui"
    ],
    env: "LLAMA_ARG_UI",
    group: "model",
    scope: "server",
    control: "toggle",
    default: "enabled",
    help: "whether to enable the Web UI",
    requiresRestart: true
  },
  {
    id: "no_webui_mcp_proxy",
    label: "No Webui MCP Proxy",
    flags: [
      "--ui-mcp-proxy",
      "--webui-mcp-proxy",
      "--no-ui-mcp-proxy",
      "--no-webui-mcp-proxy"
    ],
    env: "LLAMA_ARG_UI_MCP_PROXY",
    group: "model",
    scope: "server",
    control: "toggle",
    default: "disabled",
    help: "experimental: whether to enable MCP CORS proxy - do not enable in untrusted environments",
    requiresRestart: true
  },
  {
    id: "override_kv",
    label: "Override KV",
    flags: [
      "--override-kv"
    ],
    group: "model",
    scope: "server",
    control: "text",
    help: "advanced option to override model metadata by key.",
    requiresRestart: true
  },
  {
    id: "reverse_prompt",
    label: "Reverse Prompt",
    flags: [
      "-r",
      "--reverse-prompt"
    ],
    group: "model",
    scope: "server",
    control: "text",
    help: "halt generation at PROMPT, return control in interactive mode",
    requiresRestart: true
  },
  {
    id: "sleep_idle_seconds",
    label: "Sleep Idle Seconds",
    flags: [
      "--sleep-idle-seconds"
    ],
    group: "model",
    scope: "server",
    control: "int",
    default: -1,
    defaultLabel: "disabled",
    help: "number of seconds of idleness after which the server will sleep",
    requiresRestart: true
  },
  {
    id: "slot_prompt_similarity",
    label: "Slot Prompt Similarity",
    flags: [
      "-sps",
      "--slot-prompt-similarity"
    ],
    group: "model",
    scope: "server",
    control: "float",
    default: 0.1,
    defaultLabel: "0.0 = disabled",
    help: "how much the prompt of a request must match the prompt of a slot in order to use that slot",
    requiresRestart: true
  },
  {
    id: "spm_infill",
    label: "Spm Infill",
    flags: [
      "--spm-infill"
    ],
    group: "model",
    scope: "server",
    control: "toggle",
    default: "disabled",
    help: "use Suffix/Prefix/Middle pattern for infill (instead of Prefix/Suffix/Middle) as some models prefer this.",
    requiresRestart: true
  },
  {
    id: "swa_checkpoints",
    label: "Swa Checkpoints",
    flags: [
      "-ctxcp",
      "--ctx-checkpoints",
      "--swa-checkpoints"
    ],
    env: "LLAMA_ARG_CTX_CHECKPOINTS",
    group: "model",
    scope: "server",
    control: "int",
    default: 32,
    help: "max number of context checkpoints to create per slot [(more info)](https://github.com/ggml-org/llama.cpp/pull/15293)",
    requiresRestart: true
  },
  {
    id: "tags",
    label: "Tags",
    flags: [
      "--tags"
    ],
    env: "LLAMA_ARG_TAGS",
    group: "model",
    scope: "server",
    control: "text",
    help: "set model tags, comma-separated (informational, not used for routing)",
    requiresRestart: true
  },
  {
    id: "usage",
    label: "Usage",
    flags: [
      "-h",
      "--help",
      "--usage"
    ],
    group: "model",
    scope: "server",
    control: "text",
    help: "print usage and exit",
    requiresRestart: true
  },
  {
    id: "version",
    label: "Version",
    flags: [
      "--version"
    ],
    group: "model",
    scope: "server",
    control: "toggle",
    help: "show version and build info",
    requiresRestart: true
  },
  {
    id: "vision_gemma_12b_default",
    label: "Vision Gemma 12b Default",
    flags: [
      "--vision-gemma-12b-default"
    ],
    group: "model",
    scope: "server",
    control: "toggle",
    help: "use Gemma 3 12B QAT (note: can download weights from the internet)",
    requiresRestart: true
  },
  {
    id: "vision_gemma_4b_default",
    label: "Vision Gemma 4b Default",
    flags: [
      "--vision-gemma-4b-default"
    ],
    group: "model",
    scope: "server",
    control: "toggle",
    help: "use Gemma 3 4B QAT (note: can download weights from the internet)",
    requiresRestart: true
  },
  {
    id: "webui_config",
    label: "Webui Config",
    flags: [
      "--ui-config",
      "--webui-config"
    ],
    env: "LLAMA_ARG_UI_CONFIG",
    group: "model",
    scope: "server",
    control: "text",
    help: "JSON that provides default UI settings (overrides UI defaults)",
    requiresRestart: true
  },
  {
    id: "webui_config_file",
    label: "Webui Config File",
    flags: [
      "--ui-config-file",
      "--webui-config-file"
    ],
    env: "LLAMA_ARG_UI_CONFIG_FILE",
    group: "model",
    scope: "server",
    control: "path",
    help: "JSON file that provides default UI settings (overrides UI defaults)",
    requiresRestart: true
  },
  {
    id: "device",
    label: "Device",
    flags: [
      "-dev",
      "--device"
    ],
    env: "LLAMA_ARG_DEVICE",
    group: "devices",
    scope: "server",
    control: "list",
    help: "comma-separated list of devices to use for offloading (none = don't offload) use --list-devices to see a list of available devices",
    requiresRestart: true
  },
  {
    id: "device_draft",
    label: "Device Draft",
    flags: [
      "--spec-draft-device",
      "-devd",
      "--device-draft"
    ],
    group: "devices",
    scope: "server",
    control: "list",
    help: "comma-separated list of devices to use for offloading the draft model (none = don't offload) use --list-devices to see a list of available devices",
    requiresRestart: true
  },
  {
    id: "n_gpu_layers",
    label: "GPU layers",
    flags: [
      "-ngl",
      "--gpu-layers",
      "--n-gpu-layers"
    ],
    env: "LLAMA_ARG_N_GPU_LAYERS",
    group: "devices",
    scope: "server",
    control: "enum",
    default: "auto",
    help: "max.",
    requiresRestart: true
  },
  {
    id: "list_devices",
    label: "List Devices",
    flags: [
      "--list-devices"
    ],
    group: "devices",
    scope: "server",
    control: "toggle",
    help: "print list of available devices and exit",
    requiresRestart: true
  },
  {
    id: "main_gpu",
    label: "Main GPU",
    flags: [
      "-mg",
      "--main-gpu"
    ],
    env: "LLAMA_ARG_MAIN_GPU",
    group: "devices",
    scope: "server",
    control: "int",
    default: 0,
    help: "the GPU to use for the model (with split-mode = none), or for intermediate results and KV (with split-mode = row)",
    requiresRestart: true
  },
  {
    id: "n_gpu_layers_draft",
    label: "N GPU Layers Draft",
    flags: [
      "--spec-draft-ngl",
      "-ngld",
      "--gpu-layers-draft",
      "--n-gpu-layers-draft"
    ],
    env: "LLAMA_ARG_N_GPU_LAYERS_DRAFT",
    group: "devices",
    scope: "server",
    control: "enum",
    default: "auto",
    help: "max.",
    requiresRestart: true
  },
  {
    id: "split_mode",
    label: "Split mode",
    flags: [
      "-sm",
      "--split-mode"
    ],
    env: "LLAMA_ARG_SPLIT_MODE",
    group: "devices",
    scope: "server",
    control: "enum",
    options: [
      {
        value: "none"
      },
      {
        value: "layer"
      },
      {
        value: "row"
      },
      {
        value: "tensor"
      }
    ],
    help: "how to split the model across multiple GPUs, one of: - none: use one GPU only - layer (default): split layers and KV across GPUs (pipelined) - row: split weight across GPUs by rows (parallelized) - tensor: split weights and KV across GPUs (parallelized, EXPERIMENTAL)",
    requiresRestart: true
  },
  {
    id: "tensor_split",
    label: "Tensor split",
    flags: [
      "-ts",
      "--tensor-split"
    ],
    env: "LLAMA_ARG_TENSOR_SPLIT",
    group: "devices",
    scope: "server",
    control: "list",
    runtime: "device-list",
    help: "fraction of the model to offload to each GPU, comma-separated list of proportions, e.g.",
    requiresRestart: true
  },
  {
    id: "cpu_mask_batch_draft",
    label: "CPU Mask Batch Draft",
    flags: [
      "--spec-draft-cpu-mask-batch",
      "-Cbd",
      "--cpu-mask-batch-draft"
    ],
    group: "speculative",
    scope: "server",
    control: "text",
    defaultLabel: "same as --cpu-mask",
    help: "Draft model CPU affinity mask.",
    requiresRestart: true
  },
  {
    id: "cpu_mask_draft",
    label: "CPU Mask Draft",
    flags: [
      "--spec-draft-cpu-mask",
      "-Cd",
      "--cpu-mask-draft"
    ],
    group: "speculative",
    scope: "server",
    control: "text",
    defaultLabel: "same as --cpu-mask",
    help: "Draft model CPU affinity mask.",
    requiresRestart: true
  },
  {
    id: "cpu_moe_draft",
    label: "CPU Moe Draft",
    flags: [
      "--spec-draft-cpu-moe",
      "-cmoed",
      "--cpu-moe-draft"
    ],
    env: "LLAMA_ARG_SPEC_DRAFT_CPU_MOE",
    group: "speculative",
    scope: "server",
    control: "text",
    help: "keep all Mixture of Experts (MoE) weights in the CPU for the draft model",
    requiresRestart: true
  },
  {
    id: "cpu_range_draft",
    label: "CPU Range Draft",
    flags: [
      "--spec-draft-cpu-range",
      "-Crd",
      "--cpu-range-draft"
    ],
    group: "speculative",
    scope: "server",
    control: "text",
    help: "Ranges of CPUs for affinity.",
    requiresRestart: true
  },
  {
    id: "cpu_strict_batch_draft",
    label: "CPU Strict Batch Draft",
    flags: [
      "--spec-draft-cpu-strict-batch",
      "--cpu-strict-batch-draft"
    ],
    group: "speculative",
    scope: "server",
    control: "enum",
    defaultLabel: "--cpu-strict-draft",
    options: [
      {
        value: "0"
      },
      {
        value: "1"
      }
    ],
    help: "Use strict CPU placement for draft model",
    requiresRestart: true
  },
  {
    id: "cpu_strict_draft",
    label: "CPU Strict Draft",
    flags: [
      "--spec-draft-cpu-strict",
      "--cpu-strict-draft"
    ],
    group: "speculative",
    scope: "server",
    control: "enum",
    defaultLabel: "same as --cpu-strict",
    options: [
      {
        value: "0"
      },
      {
        value: "1"
      }
    ],
    help: "Use strict CPU placement for draft model",
    requiresRestart: true
  },
  {
    id: "draft_p_min",
    label: "Draft P Min",
    flags: [
      "--spec-draft-p-min",
      "--draft-p-min"
    ],
    env: "LLAMA_ARG_SPEC_DRAFT_P_MIN",
    group: "speculative",
    scope: "server",
    control: "int",
    default: 0,
    help: "minimum speculative decoding probability (greedy)",
    requiresRestart: true
  },
  {
    id: "draft_p_split",
    label: "Draft P Split",
    flags: [
      "--spec-draft-p-split",
      "--draft-p-split"
    ],
    env: "LLAMA_ARG_SPEC_DRAFT_P_SPLIT",
    group: "speculative",
    scope: "server",
    control: "float",
    default: 0.1,
    help: "speculative decoding split probability",
    requiresRestart: true
  },
  {
    id: "model_draft",
    label: "Model Draft",
    flags: [
      "--spec-draft-model",
      "-md",
      "--model-draft"
    ],
    env: "LLAMA_ARG_SPEC_DRAFT_MODEL",
    group: "speculative",
    scope: "server",
    control: "text",
    default: "unused",
    help: "draft model for speculative decoding",
    requiresRestart: true
  },
  {
    id: "n_cpu_moe_draft",
    label: "N CPU Moe Draft",
    flags: [
      "--spec-draft-n-cpu-moe",
      "--spec-draft-ncmoe",
      "-ncmoed",
      "--n-cpu-moe-draft"
    ],
    env: "LLAMA_ARG_SPEC_DRAFT_N_CPU_MOE",
    group: "speculative",
    scope: "server",
    control: "text",
    help: "keep the Mixture of Experts (MoE) weights of the first N layers in the CPU for the draft model",
    requiresRestart: true
  },
  {
    id: "no_spec_draft_backend_sampling",
    label: "No Spec Draft Backend Sampling",
    flags: [
      "--spec-draft-backend-sampling",
      "--no-spec-draft-backend-sampling"
    ],
    env: "LLAMA_ARG_SPEC_DRAFT_BACKEND_SAMPLING",
    group: "speculative",
    scope: "server",
    control: "toggle",
    default: "enabled",
    help: "offload draft sampling to the backend",
    requiresRestart: true
  },
  {
    id: "override_tensor_draft",
    label: "Override Tensor Draft",
    flags: [
      "--spec-draft-override-tensor",
      "-otd",
      "--override-tensor-draft"
    ],
    group: "speculative",
    scope: "server",
    control: "text",
    help: "override tensor buffer type for draft model",
    requiresRestart: true
  },
  {
    id: "poll_batch_draft",
    label: "Poll Batch Draft",
    flags: [
      "--spec-draft-poll-batch",
      "--poll-batch-draft"
    ],
    group: "speculative",
    scope: "server",
    control: "enum",
    defaultLabel: "--poll-draft",
    options: [
      {
        value: "0"
      },
      {
        value: "1"
      }
    ],
    help: "Use polling to wait for draft model work",
    requiresRestart: true
  },
  {
    id: "poll_draft",
    label: "Poll Draft",
    flags: [
      "--spec-draft-poll",
      "--poll-draft"
    ],
    group: "speculative",
    scope: "server",
    control: "enum",
    defaultLabel: "same as --poll",
    options: [
      {
        value: "0"
      },
      {
        value: "1"
      }
    ],
    help: "Use polling to wait for draft model work",
    requiresRestart: true
  },
  {
    id: "prio_batch_draft",
    label: "Prio Batch Draft",
    flags: [
      "--spec-draft-prio-batch",
      "--prio-batch-draft"
    ],
    group: "speculative",
    scope: "server",
    control: "int",
    default: 0,
    help: "set draft process/thread priority : 0-normal, 1-medium, 2-high, 3-realtime",
    requiresRestart: true
  },
  {
    id: "prio_draft",
    label: "Prio Draft",
    flags: [
      "--spec-draft-prio",
      "--prio-draft"
    ],
    group: "speculative",
    scope: "server",
    control: "int",
    default: 0,
    help: "set draft process/thread priority : 0-normal, 1-medium, 2-high, 3-realtime",
    requiresRestart: true
  },
  {
    id: "spec_default",
    label: "Spec Default",
    flags: [
      "--spec-default"
    ],
    group: "speculative",
    scope: "server",
    control: "toggle",
    help: "enable default speculative decoding config",
    requiresRestart: true
  },
  {
    id: "spec_draft_n_max",
    label: "Spec Draft N Max",
    flags: [
      "--spec-draft-n-max"
    ],
    env: "LLAMA_ARG_SPEC_DRAFT_N_MAX",
    group: "speculative",
    scope: "server",
    control: "int",
    default: 3,
    help: "number of tokens to draft for speculative decoding",
    requiresRestart: true
  },
  {
    id: "spec_draft_n_min",
    label: "Spec Draft N Min",
    flags: [
      "--spec-draft-n-min"
    ],
    env: "LLAMA_ARG_SPEC_DRAFT_N_MIN",
    group: "speculative",
    scope: "server",
    control: "int",
    default: 0,
    help: "minimum number of draft tokens to use for speculative decoding",
    requiresRestart: true
  },
  {
    id: "spec_ngram_map_k_min_hits",
    label: "Spec Ngram Map K Min Hits",
    flags: [
      "--spec-ngram-map-k-min-hits"
    ],
    group: "speculative",
    scope: "server",
    control: "int",
    default: 1,
    help: "minimum hits for ngram-map-k speculative decoding",
    requiresRestart: true
  },
  {
    id: "spec_ngram_map_k_size_m",
    label: "Spec Ngram Map K Size M",
    flags: [
      "--spec-ngram-map-k-size-m"
    ],
    group: "speculative",
    scope: "server",
    control: "int",
    default: 48,
    help: "ngram size M for ngram-map-k speculative decoding, length of draft m-gram",
    requiresRestart: true
  },
  {
    id: "spec_ngram_map_k_size_n",
    label: "Spec Ngram Map K Size N",
    flags: [
      "--spec-ngram-map-k-size-n"
    ],
    group: "speculative",
    scope: "server",
    control: "int",
    default: 12,
    help: "ngram size N for ngram-map-k speculative decoding, length of lookup n-gram",
    requiresRestart: true
  },
  {
    id: "spec_ngram_map_k4v_min_hits",
    label: "Spec Ngram Map K4v Min Hits",
    flags: [
      "--spec-ngram-map-k4v-min-hits"
    ],
    group: "speculative",
    scope: "server",
    control: "int",
    default: 1,
    help: "minimum hits for ngram-map-k4v speculative decoding",
    requiresRestart: true
  },
  {
    id: "spec_ngram_map_k4v_size_m",
    label: "Spec Ngram Map K4v Size M",
    flags: [
      "--spec-ngram-map-k4v-size-m"
    ],
    group: "speculative",
    scope: "server",
    control: "int",
    default: 48,
    help: "ngram size M for ngram-map-k4v speculative decoding, length of draft m-gram",
    requiresRestart: true
  },
  {
    id: "spec_ngram_map_k4v_size_n",
    label: "Spec Ngram Map K4v Size N",
    flags: [
      "--spec-ngram-map-k4v-size-n"
    ],
    group: "speculative",
    scope: "server",
    control: "int",
    default: 12,
    help: "ngram size N for ngram-map-k4v speculative decoding, length of lookup n-gram",
    requiresRestart: true
  },
  {
    id: "spec_ngram_mod_n_match",
    label: "Spec Ngram Mod N Match",
    flags: [
      "--spec-ngram-mod-n-match"
    ],
    group: "speculative",
    scope: "server",
    control: "int",
    default: 24,
    help: "ngram-mod lookup length",
    requiresRestart: true
  },
  {
    id: "spec_ngram_mod_n_max",
    label: "Spec Ngram Mod N Max",
    flags: [
      "--spec-ngram-mod-n-max"
    ],
    group: "speculative",
    scope: "server",
    control: "int",
    default: 64,
    help: "maximum number of ngram tokens to use for ngram-based speculative decoding",
    requiresRestart: true
  },
  {
    id: "spec_ngram_mod_n_min",
    label: "Spec Ngram Mod N Min",
    flags: [
      "--spec-ngram-mod-n-min"
    ],
    group: "speculative",
    scope: "server",
    control: "int",
    default: 48,
    help: "minimum number of ngram tokens to use for ngram-based speculative decoding",
    requiresRestart: true
  },
  {
    id: "spec_ngram_simple_min_hits",
    label: "Spec Ngram Simple Min Hits",
    flags: [
      "--spec-ngram-simple-min-hits"
    ],
    group: "speculative",
    scope: "server",
    control: "int",
    default: 1,
    help: "minimum hits for ngram-simple speculative decoding",
    requiresRestart: true
  },
  {
    id: "spec_ngram_simple_size_m",
    label: "Spec Ngram Simple Size M",
    flags: [
      "--spec-ngram-simple-size-m"
    ],
    group: "speculative",
    scope: "server",
    control: "int",
    default: 48,
    help: "ngram size M for ngram-simple speculative decoding, length of draft m-gram",
    requiresRestart: true
  },
  {
    id: "spec_ngram_simple_size_n",
    label: "Spec Ngram Simple Size N",
    flags: [
      "--spec-ngram-simple-size-n"
    ],
    group: "speculative",
    scope: "server",
    control: "int",
    default: 12,
    help: "ngram size N for ngram-simple speculative decoding, length of lookup n-gram",
    requiresRestart: true
  },
  {
    id: "spec_type",
    label: "Spec Type",
    flags: [
      "--spec-type"
    ],
    env: "LLAMA_ARG_SPEC_TYPE",
    group: "speculative",
    scope: "server",
    control: "list",
    default: "none",
    help: "comma-separated list of types of speculative decoding to use",
    requiresRestart: true
  },
  {
    id: "threads_batch_draft",
    label: "Threads Batch Draft",
    flags: [
      "--spec-draft-threads-batch",
      "-tbd",
      "--threads-batch-draft"
    ],
    group: "speculative",
    scope: "server",
    control: "text",
    defaultLabel: "same as --threads-draft",
    help: "number of threads to use during batch and prompt processing",
    requiresRestart: true
  },
  {
    id: "threads_draft",
    label: "Threads Draft",
    flags: [
      "--spec-draft-threads",
      "-td",
      "--threads-draft"
    ],
    group: "speculative",
    scope: "server",
    control: "text",
    defaultLabel: "same as --threads",
    help: "number of threads to use during generation",
    requiresRestart: true
  },
  {
    id: "api_key",
    label: "API Key",
    flags: [
      "--api-key"
    ],
    env: "LLAMA_API_KEY",
    group: "server",
    scope: "server",
    control: "list",
    default: "none",
    help: "API key to use for authentication, multiple keys can be provided as a comma-separated list",
    requiresRestart: true
  },
  {
    id: "api_key_file",
    label: "API Key File",
    flags: [
      "--api-key-file"
    ],
    env: "LLAMA_ARG_API_KEY_FILE",
    group: "server",
    scope: "server",
    control: "path",
    default: "none",
    help: "path to file containing API keys, one per line; lines starting with a hash are treated as comments",
    requiresRestart: true
  },
  {
    id: "api_prefix",
    label: "API Prefix",
    flags: [
      "--api-prefix"
    ],
    env: "LLAMA_ARG_API_PREFIX",
    group: "server",
    scope: "server",
    control: "text",
    default: "",
    help: "prefix path the server serves from, without the trailing slash",
    requiresRestart: true
  },
  {
    id: "cors_headers",
    label: "Cors Headers",
    flags: [
      "--cors-headers"
    ],
    env: "LLAMA_ARG_CORS_HEADERS",
    group: "server",
    scope: "server",
    control: "list",
    default: "*",
    help: "comma-separated list of allowed headers for CORS",
    requiresRestart: true
  },
  {
    id: "cors_methods",
    label: "Cors Methods",
    flags: [
      "--cors-methods"
    ],
    env: "LLAMA_ARG_CORS_METHODS",
    group: "server",
    scope: "server",
    control: "list",
    default: "GET",
    defaultLabel: "POST, DELETE, OPTIONS",
    help: "comma-separated list of allowed methods for CORS",
    requiresRestart: true
  },
  {
    id: "cors_origins",
    label: "Cors Origins",
    flags: [
      "--cors-origins"
    ],
    env: "LLAMA_ARG_CORS_ORIGINS",
    group: "server",
    scope: "server",
    control: "list",
    default: "*",
    help: "comma-separated list of allowed origins for CORS if set to special value 'localhost', reflect the Origin header only if it is localhost",
    requiresRestart: true
  },
  {
    id: "host",
    label: "Host",
    flags: [
      "--host"
    ],
    env: "LLAMA_ARG_HOST",
    group: "server",
    scope: "server",
    control: "text",
    default: "127.0.0.1",
    help: "ip address to listen, or bind to an UNIX socket if the address ends with .sock",
    requiresRestart: true
  },
  {
    id: "media_path",
    label: "Media Path",
    flags: [
      "--media-path"
    ],
    group: "server",
    scope: "server",
    control: "path",
    default: "disabled",
    help: "directory for loading local media files; files can be accessed via file:// URLs using relative paths",
    requiresRestart: true
  },
  {
    id: "metrics",
    label: "Metrics",
    flags: [
      "--metrics"
    ],
    env: "LLAMA_ARG_ENDPOINT_METRICS",
    group: "server",
    scope: "server",
    control: "toggle",
    default: "disabled",
    help: "enable prometheus compatible metrics endpoint",
    requiresRestart: true
  },
  {
    id: "models_dir",
    label: "Models Dir",
    flags: [
      "--models-dir"
    ],
    env: "LLAMA_ARG_MODELS_DIR",
    group: "server",
    scope: "server",
    control: "path",
    default: "disabled",
    help: "directory containing models for the router server",
    requiresRestart: true
  },
  {
    id: "models_max",
    label: "Models Max",
    flags: [
      "--models-max"
    ],
    env: "LLAMA_ARG_MODELS_MAX",
    group: "server",
    scope: "server",
    control: "int",
    default: 4,
    defaultLabel: "0 = unlimited",
    help: "for router server, maximum number of models to load simultaneously",
    requiresRestart: true
  },
  {
    id: "models_preset",
    label: "Models Preset",
    flags: [
      "--models-preset"
    ],
    env: "LLAMA_ARG_MODELS_PRESET",
    group: "server",
    scope: "server",
    control: "path",
    default: "disabled",
    help: "path to INI file containing model presets for the router server",
    requiresRestart: true
  },
  {
    id: "path",
    label: "Path",
    flags: [
      "--path"
    ],
    env: "LLAMA_ARG_STATIC_PATH",
    group: "server",
    scope: "server",
    control: "path",
    default: "",
    help: "path to serve static files from",
    requiresRestart: true
  },
  {
    id: "port",
    label: "Port",
    flags: [
      "--port"
    ],
    env: "LLAMA_ARG_PORT",
    group: "server",
    scope: "server",
    control: "int",
    default: 8080,
    help: "port to listen",
    requiresRestart: true
  },
  {
    id: "props",
    label: "Props",
    flags: [
      "--props"
    ],
    env: "LLAMA_ARG_ENDPOINT_PROPS",
    group: "server",
    scope: "server",
    control: "toggle",
    default: "disabled",
    help: "enable changing global properties via POST /props",
    requiresRestart: true
  },
  {
    id: "reuse_port",
    label: "Reuse Port",
    flags: [
      "--reuse-port"
    ],
    env: "LLAMA_ARG_REUSE_PORT",
    group: "server",
    scope: "server",
    control: "toggle",
    default: "disabled",
    help: "allow multiple sockets to bind to the same port",
    requiresRestart: true
  },
  {
    id: "slot_save_path",
    label: "Slot Save Path",
    flags: [
      "--slot-save-path"
    ],
    group: "server",
    scope: "server",
    control: "path",
    default: "disabled",
    help: "path to save slot kv cache",
    requiresRestart: true
  },
  {
    id: "sse_ping_interval",
    label: "Sse Ping Interval",
    flags: [
      "--sse-ping-interval"
    ],
    env: "LLAMA_ARG_SSE_PING_INTERVAL",
    group: "server",
    scope: "server",
    control: "text",
    help: "server SSE ping interval in seconds (-1 = disabled, default: 30)",
    requiresRestart: true
  },
  {
    id: "ssl_cert_file",
    label: "SSL Cert File",
    flags: [
      "--ssl-cert-file"
    ],
    env: "LLAMA_ARG_SSL_CERT_FILE",
    group: "server",
    scope: "server",
    control: "path",
    help: "path to file a PEM-encoded SSL certificate",
    requiresRestart: true
  },
  {
    id: "ssl_key_file",
    label: "SSL Key File",
    flags: [
      "--ssl-key-file"
    ],
    env: "LLAMA_ARG_SSL_KEY_FILE",
    group: "server",
    scope: "server",
    control: "path",
    help: "path to file a PEM-encoded SSL private key",
    requiresRestart: true
  },
  {
    id: "timeout",
    label: "Timeout",
    flags: [
      "-to",
      "--timeout"
    ],
    env: "LLAMA_ARG_TIMEOUT",
    group: "server",
    scope: "server",
    control: "int",
    default: 3600,
    help: "server read/write timeout in seconds",
    requiresRestart: true
  },
  {
    id: "mcp_servers_config",
    label: "MCP Servers Config",
    flags: [
      "--mcp-servers-config"
    ],
    env: "LLAMA_ARG_MCP_SERVERS_CONFIG",
    group: "agents",
    scope: "server",
    control: "path",
    default: "none",
    help: "experimental: path to JSON file with MCP server definitions (Cursor-compatible format) - do not enable in untrusted environments note: for security reasons, this will limit --cors-origins to localhost by default",
    requiresRestart: true
  },
  {
    id: "mcp_servers_json",
    label: "MCP Servers Json",
    flags: [
      "--mcp-servers-json"
    ],
    env: "LLAMA_ARG_MCP_SERVERS_JSON",
    group: "agents",
    scope: "server",
    control: "enum",
    default: "none",
    help: "experimental: inline JSON with MCP server definitions (Cursor-compatible format) - do not enable in untrusted environments note: for security reasons, this will limit --cors-origins to localhost by default",
    requiresRestart: true
  },
  {
    id: "tools",
    label: "Tools",
    flags: [
      "--tools"
    ],
    env: "LLAMA_ARG_TOOLS",
    group: "agents",
    scope: "server",
    control: "text",
    default: "no tools",
    help: "experimental: whether to enable built-in tools for AI agents - do not enable in untrusted environments specify \"all\" to enable all tools available tools: read_file, file_glob_search, grep_search, exec_shell_command, write_file, edit_file, get_info note: for security reasons, t...",
    requiresRestart: true
  },
  {
    id: "tools_runtime",
    label: "Tools Runtime",
    flags: [
      "--tools-runtime"
    ],
    env: "LLAMA_ARG_TOOLS_RUNTIME",
    group: "agents",
    scope: "server",
    control: "enum",
    default: "none",
    defaultLabel: "use host environment",
    help: "experimental: run tools in a separate runtime environment available options: 'docker:<image>', 'podman:<image>': spin up a new container and reuse it for all invocations, clean up on server exit 'docker-container:<id>', 'podman-container:<id>': use an existing container by ID,...",
    requiresRestart: true
  },
  {
    id: "embd_gemma_default",
    label: "Embd Gemma Default",
    flags: [
      "--embd-gemma-default"
    ],
    group: "multimodal",
    scope: "server",
    control: "toggle",
    help: "use default EmbeddingGemma model (note: can download weights from the internet)",
    requiresRestart: true
  },
  {
    id: "embd_normalize",
    label: "Embd Normalize",
    flags: [
      "--embd-normalize"
    ],
    group: "multimodal",
    scope: "server",
    control: "int",
    default: 2,
    help: "normalisation for embeddings (-1=none, 0=max absolute int16, 1=taxicab, 2=euclidean, >2=p-norm)",
    requiresRestart: true
  },
  {
    id: "fim_qwen_1",
    label: "FIM Qwen 1",
    flags: [
      "--fim-qwen-1"
    ],
    group: "multimodal",
    scope: "server",
    control: "text",
    help: "use default Qwen 2.5 Coder 1.5B (note: can download weights from the internet)",
    requiresRestart: true
  },
  {
    id: "fim_qwen_14b_spec",
    label: "FIM Qwen 14b Spec",
    flags: [
      "--fim-qwen-14b-spec"
    ],
    group: "multimodal",
    scope: "server",
    control: "toggle",
    help: "use Qwen 2.5 Coder 14B + 0.5B draft for speculative decoding (note: can download weights from the internet)",
    requiresRestart: true
  },
  {
    id: "fim_qwen_30b_default",
    label: "FIM Qwen 30b Default",
    flags: [
      "--fim-qwen-30b-default"
    ],
    group: "multimodal",
    scope: "server",
    control: "toggle",
    help: "use default Qwen 3 Coder 30B A3B Instruct (note: can download weights from the internet)",
    requiresRestart: true
  },
  {
    id: "fim_qwen_3b_default",
    label: "FIM Qwen 3b Default",
    flags: [
      "--fim-qwen-3b-default"
    ],
    group: "multimodal",
    scope: "server",
    control: "toggle",
    help: "use default Qwen 2.5 Coder 3B (note: can download weights from the internet)",
    requiresRestart: true
  },
  {
    id: "fim_qwen_7b_default",
    label: "FIM Qwen 7b Default",
    flags: [
      "--fim-qwen-7b-default"
    ],
    group: "multimodal",
    scope: "server",
    control: "toggle",
    help: "use default Qwen 2.5 Coder 7B (note: can download weights from the internet)",
    requiresRestart: true
  },
  {
    id: "fim_qwen_7b_spec",
    label: "FIM Qwen 7b Spec",
    flags: [
      "--fim-qwen-7b-spec"
    ],
    group: "multimodal",
    scope: "server",
    control: "toggle",
    help: "use Qwen 2.5 Coder 7B + 0.5B draft for speculative decoding (note: can download weights from the internet)",
    requiresRestart: true
  },
  {
    id: "image_max_tokens",
    label: "Image Max Tokens",
    flags: [
      "--image-max-tokens"
    ],
    env: "LLAMA_ARG_IMAGE_MAX_TOKENS",
    group: "multimodal",
    scope: "server",
    control: "text",
    default: "read from model",
    help: "maximum number of tokens each image can take, only used by vision models with dynamic resolution",
    requiresRestart: true
  },
  {
    id: "image_min_tokens",
    label: "Image Min Tokens",
    flags: [
      "--image-min-tokens"
    ],
    env: "LLAMA_ARG_IMAGE_MIN_TOKENS",
    group: "multimodal",
    scope: "server",
    control: "text",
    default: "read from model",
    help: "minimum number of tokens each image can take, only used by vision models with dynamic resolution",
    requiresRestart: true
  },
  {
    id: "mmproj",
    label: "MMPROJ",
    flags: [
      "-mm",
      "--mmproj"
    ],
    env: "LLAMA_ARG_MMPROJ",
    group: "multimodal",
    scope: "server",
    control: "path",
    help: "path to a multimodal projector file.",
    requiresRestart: true
  },
  {
    id: "mmproj_device",
    label: "MMPROJ Device",
    flags: [
      "-mmdev",
      "--mmproj-device"
    ],
    env: "MTMD_BACKEND_DEVICE",
    group: "multimodal",
    scope: "server",
    control: "text",
    help: "device to use for multimodal projector (none = don't offload, default: auto) use --list-devices to see a list of available devices",
    requiresRestart: true
  },
  {
    id: "mmproj_url",
    label: "MMPROJ URL",
    flags: [
      "-mmu",
      "--mmproj-url"
    ],
    env: "LLAMA_ARG_MMPROJ_URL",
    group: "multimodal",
    scope: "server",
    control: "text",
    help: "URL to a multimodal projector file.",
    requiresRestart: true
  },
  {
    id: "mtmd_batch_max_tokens",
    label: "Mtmd Batch Max Tokens",
    flags: [
      "--mtmd-batch-max-tokens"
    ],
    env: "LLAMA_ARG_MTMD_BATCH_MAX_TOKENS",
    group: "multimodal",
    scope: "server",
    control: "int",
    default: 1024,
    help: "maximum number of image tokens per batch when encoding images",
    requiresRestart: true
  },
  {
    id: "pooling",
    label: "Pooling",
    flags: [
      "--pooling"
    ],
    env: "LLAMA_ARG_POOLING",
    group: "multimodal",
    scope: "server",
    control: "enum",
    options: [
      {
        value: "none"
      },
      {
        value: "mean"
      },
      {
        value: "cls"
      },
      {
        value: "last"
      },
      {
        value: "rank"
      }
    ],
    help: "pooling type for embeddings, use model default if unspecified",
    requiresRestart: true
  },
  {
    id: "reranking",
    label: "Reranking",
    flags: [
      "--rerank",
      "--reranking"
    ],
    env: "LLAMA_ARG_RERANKING",
    group: "multimodal",
    scope: "server",
    control: "toggle",
    default: "disabled",
    help: "enable reranking endpoint on server",
    requiresRestart: true
  },
  {
    id: "chat_template",
    label: "Chat Template",
    flags: [
      "--chat-template"
    ],
    env: "LLAMA_ARG_CHAT_TEMPLATE",
    group: "chat",
    scope: "server",
    control: "text",
    default: "template taken from model's metadata",
    help: "set custom jinja chat template if suffix/prefix are specified, template will be disabled only commonly used templates are accepted (unless --jinja is set before this flag): list of built-in templates: bailing, bailing-think, bailing2, chatglm3, chatglm4, chatml, command-r, dee...",
    requiresRestart: true
  },
  {
    id: "chat_template_file",
    label: "Chat Template File",
    flags: [
      "--chat-template-file"
    ],
    env: "LLAMA_ARG_CHAT_TEMPLATE_FILE",
    group: "chat",
    scope: "server",
    control: "path",
    default: "template taken from model's metadata",
    help: "set custom jinja chat template file if suffix/prefix are specified, template will be disabled only commonly used templates are accepted (unless --jinja is set before this flag): list of built-in templates: bailing, bailing-think, bailing2, chatglm3, chatglm4, chatml, command-r...",
    requiresRestart: true
  },
  {
    id: "chat_template_kwargs",
    label: "Chat Template Kwargs",
    flags: [
      "--chat-template-kwargs"
    ],
    env: "LLAMA_ARG_CHAT_TEMPLATE_KWARGS",
    group: "chat",
    scope: "request",
    control: "text",
    help: "sets additional params for the json template parser, must be a valid json object string, e.g."
  },
  {
    id: "no_reasoning_preserve",
    label: "No Reasoning Preserve",
    flags: [
      "--reasoning-preserve",
      "--no-reasoning-preserve"
    ],
    env: "LLAMA_ARG_REASONING_PRESERVE",
    group: "chat",
    scope: "server",
    control: "text",
    default: "template default",
    help: "preserve reasoning trace in the full history, not just the last assistant message compatible with certain templates having 'supports_preserve_reasoning' capability example: https://docs.z.ai/guides/capabilities/thinking-mode#preserved-thinking",
    requiresRestart: true
  },
  {
    id: "no_skip_chat_parsing",
    label: "No Skip Chat Parsing",
    flags: [
      "--skip-chat-parsing",
      "--no-skip-chat-parsing"
    ],
    env: "LLAMA_ARG_SKIP_CHAT_PARSING",
    group: "chat",
    scope: "server",
    control: "toggle",
    default: "disabled",
    help: "force a pure content parser, even if a Jinja template is specified; model will output everything in the content section, including any reasoning and/or tool calls",
    requiresRestart: true
  },
  {
    id: "reasoning",
    label: "Reasoning",
    flags: [
      "-rea",
      "--reasoning"
    ],
    env: "LLAMA_ARG_REASONING",
    group: "chat",
    scope: "request",
    control: "enum",
    options: [
      {
        value: "on"
      },
      {
        value: "off"
      },
      {
        value: "auto"
      }
    ],
    help: "Use reasoning/thinking in the chat ('on', 'off', or 'auto', default: 'auto' (detect from template))"
  },
  {
    id: "reasoning_budget",
    label: "Reasoning Budget",
    flags: [
      "--reasoning-budget"
    ],
    env: "LLAMA_ARG_THINK_BUDGET",
    group: "chat",
    scope: "request",
    control: "int",
    default: -1,
    help: "token budget for thinking: -1 for unrestricted, 0 for immediate end, N>0 for token budget"
  },
  {
    id: "reasoning_budget_message",
    label: "Reasoning Budget Message",
    flags: [
      "--reasoning-budget-message"
    ],
    env: "LLAMA_ARG_THINK_BUDGET_MESSAGE",
    group: "chat",
    scope: "request",
    control: "enum",
    default: "none",
    help: "message injected before the end-of-thinking tag when reasoning budget is exhausted"
  },
  {
    id: "reasoning_effort",
    label: "Reasoning Effort",
    flags: [
      "--reasoning-effort"
    ],
    env: "LLAMA_ARG_REASONING_EFFORT",
    group: "chat",
    scope: "request",
    control: "text",
    default: "default",
    help: "reasoning effort level given to the chat template: 'default' to keep the template default, or a level such as 'minimal', 'low', 'medium', 'high', 'xhigh' or 'max'"
  },
  {
    id: "reasoning_format",
    label: "Reasoning Format",
    flags: [
      "--reasoning-format"
    ],
    env: "LLAMA_ARG_THINK",
    group: "chat",
    scope: "request",
    control: "enum",
    default: "auto",
    help: "controls whether thought tags are allowed and/or extracted from the response, and in which format they're returned; one of: - none: leaves thoughts unparsed in `message.content` - deepseek: puts thoughts in `message.reasoning_content` - deepseek-legacy: keeps `<think>` tags in..."
  },
  {
    id: "log_colors",
    label: "Log Colors",
    flags: [
      "--log-colors"
    ],
    env: "LLAMA_ARG_LOG_COLORS",
    group: "logging",
    scope: "server",
    control: "enum",
    options: [
      {
        value: "on"
      },
      {
        value: "off"
      },
      {
        value: "auto"
      }
    ],
    help: "Set colored logging ('on', 'off', or 'auto', default: 'auto') 'auto' enables colors when output is to a terminal",
    requiresRestart: true
  },
  {
    id: "log_disable",
    label: "Log Disable",
    flags: [
      "--log-disable"
    ],
    group: "logging",
    scope: "server",
    control: "toggle",
    help: "Log disable",
    requiresRestart: true
  },
  {
    id: "log_file",
    label: "Log File",
    flags: [
      "--log-file"
    ],
    env: "LLAMA_ARG_LOG_FILE",
    group: "logging",
    scope: "server",
    control: "path",
    help: "Log to file",
    requiresRestart: true
  },
  {
    id: "log_prompts_dir",
    label: "Log Prompts Dir",
    flags: [
      "--log-prompts-dir"
    ],
    group: "logging",
    scope: "server",
    control: "path",
    help: "Log prompts to directory (auto-created if not present; only used for debugging, default: disabled)",
    requiresRestart: true
  },
  {
    id: "log_verbose",
    label: "Log Verbose",
    flags: [
      "-v",
      "--verbose",
      "--log-verbose"
    ],
    group: "logging",
    scope: "server",
    control: "text",
    help: "Set verbosity level to infinity (i.e.",
    requiresRestart: true
  },
  {
    id: "log_verbosity",
    label: "Log Verbosity",
    flags: [
      "-lv",
      "--verbosity",
      "--log-verbosity"
    ],
    env: "LLAMA_ARG_LOG_VERBOSITY",
    group: "logging",
    scope: "server",
    control: "int",
    default: 3,
    help: "Set the verbosity threshold.",
    requiresRestart: true
  },
  {
    id: "offline",
    label: "Offline",
    flags: [
      "--offline"
    ],
    env: "LLAMA_ARG_OFFLINE",
    group: "logging",
    scope: "server",
    control: "toggle",
    help: "Offline mode: forces use of cache, prevents network access",
    requiresRestart: true
  },
  {
    id: "special",
    label: "Special",
    flags: [
      "-sp",
      "--special"
    ],
    group: "logging",
    scope: "server",
    control: "toggle",
    default: "false",
    help: "special tokens output enabled",
    requiresRestart: true
  },
  {
    id: "defrag_thold",
    label: "Defrag Thold",
    flags: [
      "-dt",
      "--defrag-thold"
    ],
    env: "LLAMA_ARG_DEFRAG_THOLD",
    group: "archive",
    scope: "archive",
    control: "text",
    help: "KV cache defragmentation threshold (DEPRECATED)",
    deprecated: {}
  },
  {
    id: "draft_max",
    label: "Draft Max",
    flags: [
      "--draft",
      "--draft-n",
      "--draft-max"
    ],
    env: "LLAMA_ARG_DRAFT_MAX",
    group: "archive",
    scope: "archive",
    control: "text",
    help: "the argument has been removed.",
    deprecated: {}
  },
  {
    id: "draft_n_min",
    label: "Draft N Min",
    flags: [
      "--draft-min",
      "--draft-n-min"
    ],
    env: "LLAMA_ARG_DRAFT_MIN",
    group: "archive",
    scope: "archive",
    control: "text",
    help: "the argument has been removed.",
    deprecated: {}
  },
  {
    id: "mlock",
    label: "Mlock",
    flags: [
      "--mlock"
    ],
    env: "LLAMA_ARG_MLOCK",
    group: "archive",
    scope: "archive",
    control: "toggle",
    help: "DEPRECATED in favor of `--load-mode`: force system to keep model in RAM rather than swapping or compressing",
    deprecated: {}
  },
  {
    id: "no_direct_io",
    label: "No Direct Io",
    flags: [
      "-dio",
      "--direct-io",
      "-ndio",
      "--no-direct-io"
    ],
    env: "LLAMA_ARG_DIO",
    group: "archive",
    scope: "archive",
    control: "text",
    help: "DEPRECATED in favor of `--load-mode`: use DirectIO if available",
    deprecated: {}
  },
  {
    id: "no_mmap",
    label: "No Mmap",
    flags: [
      "--mmap",
      "--no-mmap"
    ],
    env: "LLAMA_ARG_MMAP",
    group: "archive",
    scope: "archive",
    control: "text",
    help: "DEPRECATED in favor of `--load-mode`: whether to memory-map model.",
    deprecated: {}
  },
  {
    id: "spec_ngram_min_hits",
    label: "Spec Ngram Min Hits",
    flags: [
      "--spec-ngram-min-hits"
    ],
    group: "archive",
    scope: "archive",
    control: "text",
    help: "the argument has been removed.",
    deprecated: {}
  },
  {
    id: "spec_ngram_size_m",
    label: "Spec Ngram Size M",
    flags: [
      "--spec-ngram-size-m"
    ],
    group: "archive",
    scope: "archive",
    control: "text",
    help: "the argument has been removed.",
    deprecated: {}
  },
  {
    id: "spec_ngram_size_n",
    label: "Spec Ngram Size N",
    flags: [
      "--spec-ngram-size-n"
    ],
    group: "archive",
    scope: "archive",
    control: "text",
    help: "the argument has been removed.",
    deprecated: {}
  }
]

export const PARAM_BY_ID = Object.fromEntries(LLAMA_PARAMS.map((p) => [p.id, p])) as Record<string, ParamDef>;

export const PARAMS_BY_GROUP: Record<ParamGroup, ParamDef[]> = LLAMA_PARAMS.reduce(
  (acc, p) => ((acc[p.group] ||= []).push(p), acc),
  {} as Record<ParamGroup, ParamDef[]>,
);

export const GROUP_ORDER: ParamGroup[] = ["speed","memory","context","sampling","model","devices","speculative","server","agents","multimodal","chat","logging","archive"];

